- .travis.yml
`NPM_TOKEN` holds the token we need to use when publishing to NPM. On
PR builds from forks, this is not present, so we should not add it to
the .npmrc folder in this case.
Also, remove setting our pypi proxy from the list of sources.
> Only set NPM_TOKEN on secure builds

- examples/examples_test.go
- examples/serverless/index.ts
- examples/serverless/package.json
- examples/serverless/yarn.lock
- overlays/nodejs/serverless/function.ts
- sdk/nodejs/serverless/function.ts
Alternative fix for #260, adds tests and makes a more targeted fix than #261 which appears to introduce other issues.
Use path APIs instead of regexp in workaround for incorrect package names coming from `read-package-tree` dependency when seeing organization-scoped packages.
Add tests for additional cases of organization-scoped packages (at the root as well as nested).
> Fix detection of org-scoped packages

- overlays/nodejs/autoscaling/notificationType.ts
- resources.go
- sdk/nodejs/autoscaling/index.ts
- sdk/nodejs/autoscaling/notification.ts
- sdk/nodejs/autoscaling/notificationType.ts
- sdk/nodejs/tsconfig.json
This pull request adds a new overlay for nodejs, defining a union type of valid Autoscaling Notification Types, and overrides the `notifications` property of the aws.autoscaling.Notification type to accept an array of these instead of raw strings.
Some outstanding questions:
I've opened the pull request early in order to take advantage of the properly configured Travis CI building for PRs, and don't anticipate this will be ready to merge without further work.
> Add autoscaling NotificationType union and overlay

- resources.go
- sdk/nodejs/package.json
- sdk/python/setup.py
This fixes the following warning from yarn when building:
```
warning package.json: License should be a valid SPDX license expression
```
I'm not 100% sure that this has no negative impact on Python, however.
> Use "Apache-2.0" for NPM licenses as per SPDX

- overlays/nodejs/iam/documents.ts
- sdk/nodejs/iam/documents.ts
This commit adds a new function, `assumeRolePolicyForPrincipal`, which constructs a well-formed role assumption policy for a given Principal. This is useful when constructing IAM roles using Pulumi.
> iam: Add iam.assumeRolePolicyForPrincipal function

- overlays/nodejs/serverless/function.ts
- sdk/nodejs/serverless/function.ts
This is targeted fix to add an environment variable map to the `aws.serverless.Function` type, as an interim step to allowing it to configure all facets of a Lambda function.
> Add `environment` to `aws.serverless.Function`

- resources.go
- sdk/nodejs/iam/rolePolicy.ts
This brings `RolePolicy` in line with `RolePolicyAttachment` in accepting a `Role` rather than requiring the ID as a `string`.
> iam: Override role on RolePolicy to accept a Role

- overlays/nodejs/serverless/function.ts
- sdk/nodejs/serverless/function.ts
Customer request from @tirke.  This enables proper .js support in the AWS cloud console:
Note: this will mean that any and all pulumi updates will show a change to lambdas.
> Add the .js extension to our generate closure code file.

- examples/minimal/package.json
- examples/serverless-raw/package.json
- examples/serverless/package.json
- examples/webserver-comp/package.json
- examples/webserver/package.json
- examples/webserver/variants/get/package.json
- examples/webserver/variants/ssh/package.json
- examples/webserver/variants/ssh_description/package.json
- examples/webserver/variants/zones/package.json
- tests/delete_before_create/mount_target/step1/package.json
- tests/regression/package.json
- tests/serverless_functions/package.json
This gets rid of all the:
```
warning package.json: License should be a valid SPDX license expression
warning @pulumi/aws-infra@${VERSION}: License should be a valid SPDX license expression
```
messages that show up while building.
> Add license items to package.json.

- resources.go
- sdk/go/aws/elasticloadbalancingv2/listener.go
- sdk/nodejs/elasticloadbalancingv2/listener.ts
- sdk/python/pulumi_aws/elasticloadbalancingv2/listener.py
This pull request sets `MaxItemsOne` on the `default_action` field of `aws.elasticloadbalancingv2.TargetGroup`, and renames it to be singular. This fix should eventually be upstreamed to the HashiCorp provider repo.
> elbv2: Make TargetGroup::defaultAction a single item

- overlays/nodejs/lambda/runtimes.ts
- sdk/nodejs/lambda/runtimes.ts
Support for dotnetcore2.1 was added for Lambda July 9th, 2018. 
This PR adds that option for the lambda runtime.
[AWS Announcement](https://aws.amazon.com/about-aws/whats-new/2018/06/lambda-supports-dotnetcore-twopointone/)
> Add support for dotnetcore2.1 as Lambda runtime

- resources.go
- sdk/nodejs/autoscaling/group.ts
- sdk/nodejs/ec2/instance.ts
- sdk/nodejs/ec2/launchConfiguration.ts
This pull request allows various properties in AWS resources related to autoscaling and IAM to accept relevant API objects in addition to the string representation of their ID.
- `launchConfiguration` on `aws.autoscaling.Group` will accept an `aws.ec2.LaunchConfiguration` (Fixes #292)
- `placementGroup` on `aws.autoscaling.Group` will accept an `aws.ec2.PlacementGroup` (Fixes #290)
- `iamInstanceProfile` on `aws.ec2.Instance` and `aws.ec2.LaunchConfiguration` will accept an `aws.iam.InstanceProfile` (Fixes #289)
> Allow API objects in addition to IDs for several properties

- overlays/nodejs/ec2/placementStrategy.ts
- resources.go
- sdk/nodejs/ec2/index.ts
- sdk/nodejs/ec2/placementGroup.ts
- sdk/nodejs/ec2/placementStrategy.ts
- sdk/nodejs/tsconfig.json
This commit adds a new overlay for nodejs, defining a union type of valid strategies for placement groups, and overrides the `strategy` property of the aws.ec2.PlacementGroup type to accept an array of these instead of raw strings.
Fixes #288.
> Add EC2 PlacementStrategy union and overlay

- overlays/nodejs/autoscaling/metrics.ts
- resources.go
- sdk/nodejs/autoscaling/group.ts
- sdk/nodejs/autoscaling/index.ts
- sdk/nodejs/autoscaling/metrics.ts
- sdk/nodejs/tsconfig.json
This commit adds a new overlay for nodejs, defining union types of valid metric types and granularities for autoscaling groups, and overrides the `enabledMetrics` and `metricsGranularity` propertes of the aws.autoscaling.Group` type to accept these new types instead of raw strings.
Fixes #291.
> Add Autoscaling Metrics and MetricsGranularity union and overlay

- overlays/nodejs/iam/principals.ts
- resources.go
- sdk/nodejs/iam/index.ts
- sdk/nodejs/iam/principals.ts
- sdk/nodejs/tsconfig.json
This commit adds service principals for each of the known AWS services, in order to assist with autocompletion when writing trust policies for IAM roles.
To the best of my knowledge the list is complete - however it is hard to track some of these down. The worst case right now is that missing Principals can still be constructed manually.
Fixes #322.
> Add overlay for AWS service principals

- resources.go
- Athena database autonames no longer contain '-' (#220)
- CloudWatch event targets, EC2 key pairs, RDS instances, and EFS file
systems are now auto-named. All of these resources use a property not
called "name" as their name.
Fixes #220.
Fixes #117.
> Fix a few resource names.

- examples/bucket/package.json
- examples/cloudwatch/package.json
- examples/express/package.json
- examples/logGroup/package.json
- examples/minimal/package.json
- examples/multiple-regions/package.json
- examples/queue/package.json
- examples/serverless-raw/package.json
- examples/serverless/package.json
- examples/table/package.json
- examples/topic/package.json
- examples/webserver-comp/package.json
- examples/webserver/package.json
- examples/webserver/variants/get/package.json
- examples/webserver/variants/ssh/package.json
- examples/webserver/variants/ssh_description/package.json
- examples/webserver/variants/zones/package.json
- resources.go
- sdk/nodejs/package.json
- sdk/nodejs/yarn.lock
- tests/delete_before_create/mount_target/step1/package.json
- tests/regression/package.json
- tests/serverless_functions/package.json
This prevents us from having to continually update these version numbers everywhere as we update upstream libs.  We will still need to replace these with the right non-dev values when we publish official versins.  But we had to do that anyways even when we were saying things like ~0.15.4-dev.
> Switch to the 'dev' version of our dependencies.

- examples/api/index.ts
- examples/api/step2/index.ts
- examples/api/yarn.lock
- sdk/nodejs/apigateway/experimental/api.ts
I recommend reviewing with whitespace off: https://github.com/pulumi/pulumi-aws/pull/343/files?w=1
Instead of passing multiple differnet arrays of route types, callers can just supply a 'route mapping object' where the keys are the route paths they care about, and the values are the specific types of routes.
> Change to a path-based approach to API routes in the experimental apigateway API.

- .gitignore
- resources.go
- sdk/nodejs/s3/bucket.ts
- sdk/nodejs/s3/cannedAcl.ts
- sdk/nodejs/s3/index.ts
- sdk/nodejs/tsconfig.json
This pull request adds a union type and constants for S3 canned ACLs, based on the [documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl).
> Add union type and constants for S3 Canned ACLs

- sdk/nodejs/lambda/lambdaMixins.ts
This is related to the cloud.Function work going on over in: https://github.com/pulumi/pulumi-cloud/pull/619
The core idea here is that we break CallbackFunctionArgs into two separate interfaces.  The first is a *non-generic* core part that just specifies the way for users to provide customized Lambda functionality for all properties *outside* of the javascript function call instances themselves.
Then, there is the same CallbackFunctionArgs that derives from that, is generic, and includes the optional callback-function or callback-factory-function.  
This split enables code in cloud.Function to take a dependency on the ability to configure an AWS lambda, without forcing it to also be responsible for passing along the callback-function in-situ.
> Breakout interfaces into two separate pieces.

- resources.go
- sdk/nodejs/lambda/permission.ts
Accept a string by default or a `lambda.Function` as an alternative.
> Improve target lamdba type in lambda_permission

- resources.go
Several of these changes have been upstreamed into the Terraform provider, so overriding is no longer necessary.
> Remove unnecessary MaxItemsOne: true annotations

- Gopkg.template.toml
This brings the AWS repository into line with the other Terraform-backed providers (excluding GCP), and allows the workflow for updating this repository to use `govendor-override < Gopkg.template.toml > Gopkg.toml` and removes the need for removing overrides for protocol buffers.
> Introduce Gopkg.template.toml

- sdk/nodejs/apigateway/experimental/api.ts
This commit replaces instances of `ResourceOptions` with `ComponentResourceOptions` in order that custom providers can be passed.
Fixes #391.
> Use `ComponentResourceOptions` for `apigateway.x.API`

- resources.go
- sdk/go/aws/autoscaling/group.go
- sdk/nodejs/autoscaling/group.ts
The existence of `tagsCollection` on `aws.autoscaling.Group` is to work around a limitation of HCLv1 configuration for Terraform, and while it is not the preferable way to define tags in Pulumi, is sometimes generated by tf2pulumi.
This commit fixes the type generation such that a list of maps with keys consisting of `key`, `value` and `propagate_at_launch` will work for tagging an autoscaling group.
Use of `tags` continues to be preferred.
Fixes #400.
> Don't use aws.Tags for aws.autoscaling.Group::tagsCollection

- resources.go
- sdk/nodejs/apigateway/experimental/api.ts
- sdk/nodejs/cloudwatch/eventRuleMixins.ts
- sdk/nodejs/cloudwatch/logGroupMixins.ts
- sdk/nodejs/dynamodb/dynamodbMixins.ts
- sdk/nodejs/kinesis/kinesisMixins.ts
- sdk/nodejs/lambda/lambdaMixins.ts
- sdk/nodejs/package.json
- sdk/nodejs/s3/s3Mixins.ts
- sdk/nodejs/serverless/function.ts
- sdk/nodejs/sns/snsMixins.ts
- sdk/nodejs/sqs/sqsMixins.ts
As per our friday meeting:
1. Components do not need to pass 'props' up to pulumi.ComponentResource (and, even if they did, pulumi.ComponentResource would ignore them thanks to https://github.com/pulumi/pulumi/pull/2296).
2. ComponentResources should call `registerOutputs` at the end of processing.  But should generally not include any properties with that call.  actually reporting outputs is really only intended for 'Stack' to do.
> Follow new patterns for component resources.

- README.md
This pull request updates the README file in the following ways:
1. Include a link to the instructions for updating Terraform-backed providers
2. Remove a reference to the now-deprecated `aws-serverless` repo, since the functionality is now subsumed directly into the packages in this repository.
> Include update instructions link in README

- resources.go
- sdk/nodejs/package.json
This was set to "dev" because we wanted to use the latest version of
@pulumi/pulumi while doing co-development across these repositories.
However, we should set this back as we are planning to do another
release and we want to lock to a stable version instead of just using
`dev`.
> Use latest released @pulumi/pulumi version

- resources.go
- sdk/go/aws/elasticache/replicationGroup.go
- sdk/nodejs/elasticache/replicationGroup.ts
- sdk/python/pulumi_aws/elasticache/replication_group.py
Fixes #426.
The documentation for the field requirements is [here].
[here]: https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateReplicationGroup.html
> Attach an AutoName to elasticache.ReplicationGroup::replicationGroupId

- resources.go
Since we map the deprecated `byte_match_tuple` property to `byte_match_tuple`, we also need to map `byte_match_tuples` to `byteMatchTuples` explicitly in order that the name resolution in `getInfoForPulumiName` in tfbridge matches the field we want instead of relying on default name mangling.
Fixes #429.
> Map ByteMatchSet::byteMatchTuples correctly

- Makefile
I find myself waiting on a full `make build` when I'm only adding debugging information to a provider binary fairly often - this commit splits out the Go build for the tfgen and provider binaries from the code generation and other build steps in order that it's easy to build just the provider binary while
retaining the correct version information.
Care should be taken to only make "safe" changes (e.g. adding debugging information, rather than changing the structure of resources).
If this change is acceptable I'll roll it out to the other provider repos.
> Add provider and tfgen targets to Makefile

- Gopkg.lock
This PR updates Gopkg.lock for the version generated by dep 0.5.
> Update Gopkg.lock for dep 0.5

- examples/webserver/variants/zones/index.ts
`us-west-2d` just appeared, and doesn't support `t2.micro` instances. Let's see if it supports `t3.micro` instances...
> Bump instance size to support us-west-2d AZ

- examples/examples_test.go
We had accidentally been skipping all "Short" tests during normal test runs.
> Run all tests in CI

- CHANGELOG.md
- go.mod
- go.sum
This pulls in 4acfa088d81fa3fc46e12ad9d0ebf0df5a55932f from `pulumi/terraform-provider-aws` to increase the timeout for an `aws.eks.Cluster` to 30 minutes.
> Pull in EKS Create Timeout change

- examples/multiple-regions/index.ts
- examples/multiple-regions/package.json
The recent changes in `pulumi-terraform` have changed the type of `aws.config.region` to possibly be undefined. Although we could cast here, it seems somewhat neater to just hard-code both region names instead of having one configured and one not.
> Hard code the regions for multiple-regions example

- CHANGELOG.md
- sdk/nodejs/lambda/runtimes.ts
AWS now supports this runtime, see:
https://aws.amazon.com/about-aws/whats-new/2019/05/aws_lambda_adds_support_for_node_js_v10/
> Add nodejs10.x

- CHANGELOG.md
- examples/switchrole/create-user-and-role/.gitignore
- examples/switchrole/create-user-and-role/Pulumi.yaml
- examples/switchrole/create-user-and-role/index.ts
- examples/switchrole/create-user-and-role/package.json
- examples/switchrole/create-user-and-role/tsconfig.json
- examples/switchrole/use-role/.gitignore
- examples/switchrole/use-role/Pulumi.yaml
- examples/switchrole/use-role/index.ts
- examples/switchrole/use-role/package.json
- examples/switchrole/use-role/tsconfig.json
- resources.go
- sdk/go/aws/config/config.go
- sdk/nodejs/config/vars.ts
- sdk/nodejs/provider.ts
- sdk/python/pulumi_aws/config/vars.py
- sdk/python/pulumi_aws/provider.py
This PR enhances the work done by @mi5guided in #579 to allow profiles defined via `AWS_PROFILE` to be used as well as the AWS config files.
Thanks, @mi5guided!
Fixes #252.
> Allow assuming a role via AWS_PROFILE or configuration files

- CHANGELOG.md
- resources.go
- sdk/nodejs/cloudwatch/eventRuleMixins.ts
- sdk/nodejs/cloudwatch/logGroupMixins.ts
- sdk/nodejs/dynamodb/dynamodbMixins.ts
- sdk/nodejs/kinesis/kinesisMixins.ts
- sdk/nodejs/package.json
- sdk/nodejs/s3/s3Mixins.ts
- sdk/nodejs/sns/snsMixins.ts
- sdk/nodejs/sqs/sqsMixins.ts
Note: this PR makes use of aliases!  I manually validated the appropraite behavior here.  Tagging @ellismg  for views on incorporating this into a fully fledged test in the future!
> Pass a parent along to pick up providers.

- CHANGELOG.md
- Makefile
`pandoc` will output using "smart quotes" by default, which caues the
README.rst which is included in our pyton package to include some non
ASCII characters, which blocks installs on some machines.
This change removes the use of smart quotes. The correct long term fix
is tracked by: https://github.com/pulumi/pulumi-terraform/pull/388 but
this will unblock installs of this package.
> Disable smart quotes in generated README.rst

- CHANGELOG.md
- resources.go
- sdk/nodejs/elasticsearch/domain.ts
- sdk/nodejs/elasticsearch/domainPolicy.ts
After researching this topic, I found that the ElasticSearch access
policies support almost everything (except NotPrincipal) of the IAM
PolicyDocument
Therefore, we can leverage the same resource
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-ac.html#policy-element-reference
> Add aws.iam.PolicyDocument as AltType to ElasticSearch resources

- CHANGELOG.md
- examples/bucket/index.ts
- go.mod
- go.sum
- resources.go
- sdk/nodejs/s3/bucket.ts
- sdk/nodejs/s3/index.ts
- sdk/nodejs/s3/routingRules.ts
- sdk/nodejs/tsconfig.json
I've been working on a program that adds some redirects for the GREAT WEBSITE MIGRATION OF 2019, and wished there were stronger types for this. Decided to go ahead and add these while it was fresh in my mind...
This augments the `routingRules` property to accept a strongly-typed array of objects, which helps to know which properties can be set and avoids the need to use `JSON.stringify`. This is especially helpful as some properties can only be set if other properties are not set.
Depends on a change in `pulumi-terraform` to allow JSON arrays in `TransformJSONDocument`: https://github.com/pulumi/pulumi-terraform/pull/393
Details:
https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#routing_rules
https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html#advanced-cond …
> Strongly-typed S3 bucket website routingRules

- CHANGELOG.md
- resources.go
- sdk/nodejs/ecr/repositoryPolicy.ts
Fixes: #631
As per this document,
https://docs.aws.amazon.com/AmazonECR/latest/userguide/RepositoryPolicies.html,
we can see that the policies are the same
> Add the ability to pass an aws.iam.PolicyDocument to ECR Repo policy

- CHANGELOG.md
- resources.go
- sdk/nodejs/route53/record.ts
When used in conjunction with ACM, Route53 record was not able to
be used. The output type of ACM validation is a string but the input
type of Route53 record type was a RecordType
We need to allow both!
Fixes: https://github.com/pulumi/docs/pull/1243
> Change Route53 Record Type to have AltType of RecordType

- CHANGELOG.md
- sdk/go/aws/lambda/runtime.go
I know it would be most consistent to use the same naming scheme [as with typescript](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/lambda/runtimes.ts), but since Go doesn't have string type unions, it seems that this would be favorable for the consumer to discover via intellesense (typing `Runtime...` would suggest all of these constants).
> Add Lambda runtime constants for go

- CHANGELOG.md
- sdk/nodejs/iam/documents.ts
In order to allow the passing of arguments from other resource
outputs, we should change how PolicyDocument works to allow passing
an Input<string> rather than a string. This will help our users to
avoid any unnecessary interpolation of types
> Change iam PolicyDocument to accept Input parameters

- CHANGELOG.md
- sdk/nodejs/ecs/container.ts
Adds all the missing fields relative to the latest AWS supported JSON schema for ContainerDefinitions at https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html.
Fixes #713.
> Bring aws.ecs.ContainerDefinition up to date

- CHANGELOG.md
- sdk/nodejs/ecs/container.ts
Align with https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html.
The change in type for `dependsOn` is a TypeScript-level breaking change, but the previous type was incorrect and would not have worked with ECS, so it is not in practice a breaking change for any working user code.
Related to https://github.com/pulumi/pulumi-awsx/issues/445, though we need to also make updates in the AWSX layer given current code structure.
> Update `ContainerDefinition` to latest ECS definition

- CHANGELOG.md
- sdk/nodejs/lambda/runtimes.ts
Related: #774
The NodeJS team have EOLed NodeJS 8.x on 31st December 2019. This
deprecation will warn our users that this is coming and that they
should move to a different runtime in advance
This commit also adds a deprecation to DotNetCore 1.0 which was
actually deprecated in AWS earlier in 2019
> Add a deprecation message to NodeJS 8.x in Lambda Runtimes

- go.mod
- go.sum
Fixes: #837 
An upstream PR pulled in a later version of this library that seems
to have caused some problems in our build
```
../../../../pkg/mod/golang.org/x/crypto@v0.0.0-20190923035154-9ee001bba392/ssh/terminal/util_windows.go:97:61: multiple-value "golang.org/x/sys/windows".GetCurrentProcess() in single-value context
```
This replace reverts it back to the same version. The PR that updated
this dependency was to update the terraform provider to a new tfproviderdocs
check library
> Replace for golang.org/x/sys

- CHANGELOG.md
- examples/route53/README.md
- examples/route53/index.ts
- resources.go
- sdk/dotnet/Route53/Record.cs
- sdk/go/aws/route53/record.go
- sdk/nodejs/acm/certificateValidation.ts
- sdk/nodejs/apigateway/domainName.ts
- sdk/nodejs/ec2/vpcEndpoint.ts
- sdk/nodejs/elasticloadbalancing/getHostedZoneId.ts
- sdk/nodejs/elb/getHostedZoneId.ts
- sdk/nodejs/route53/getZone.ts
- sdk/nodejs/route53/record.ts
- sdk/nodejs/route53/zone.ts
- sdk/nodejs/s3/getBucket.ts
- sdk/nodejs/ses/domainDkim.ts
- sdk/nodejs/ses/domainIdentity.ts
- sdk/nodejs/ses/domainIdentityVerification.ts
- sdk/nodejs/ses/mailFrom.ts
- sdk/python/pulumi_aws/route53/record.py
This property is used as the domain name of the DNS entry - and should never be autonamed.
This is a breaking change, but any code that is broken by this is most likely not working as intended.
> Stop autonaming `aws.route53.Record` `name` property

- CHANGELOG.md
- resources.go
As reported in https://github.com/pulumi/docs/pull/2366 we need to
change how we actually autoname the TopicRule name
The name needs to adhere to a different naming regex
https://docs.aws.amazon.com/iot/latest/apireference/API_TopicRule.html
> Change the autonaming of aws.iot.TopicRule

- scripts/go.mod
- scripts/go.sum
- scripts/publish-plugin.sh
This is required due to the new go mod module layout
> Adapt package publishing for new repo layout

- .travis.yml
Replicating: https://github.com/pulumi/pulumi/pull/4219
Accommodates the new module release pattern that includes tags for `vX.X.X` `sdk/vX.X.X`.
> update tag matching for travis release builds

- sdk/nodejs/iam/principals.ts
Just found it this is missing in the list. Nice to see that there are constants for it 👍 
I refrained to add this also outside the `Principals` modules as this is deprecated since PR https://github.com/pulumi/pulumi-aws/pull/600.
I think this small addition might not worth to be in the changelog. If you think otherwise, please tell me.
> IAM: Principals: Added ECS-tasks principal

- CHANGELOG.md
- sdk/nodejs/region.ts
I added a new region for Africa (Cape Town) af-south-1. 
I don't know if it's as easy as _just_ changing it in the `.ts` files. I have searched the repository for definitions alike in `.go`, `.py`, and `.cs` but did not find any.
> Add new region Africa (Cape Town) af-south-1

- examples/examples_test.go
Test `TestAccServerlessFunctions` is failing after I changed the IAM User we have hooked up to our CI. Not sure why the test isn't picking up the new credentials and honoring the `AWS_PROFILE` environment variable...
> Fix test failure in master

- CHANGELOG.md
- provider/go.mod
- provider/go.sum
Fixes: #997
Fixes: #1013
Fixes: #990
> Ensure autoscaling.Group.Tag and autoscaling.Group.Tags are correct schema type

- CHANGELOG.md
- sdk/nodejs/tags.ts
The recent `2.10` release included a change that caused the `tags` on resources to change shape.
> Fix aws.Tags interface to match updated codegen

- sdk/nodejs/iam/managedPolicies.ts
I removed the explicit deprecation messages from the other enums but had missed ManagedPolicies. Removing the deprecation messages since the old constants are still valid.
Related to: https://github.com/pulumi/pulumi-aws/pull/1166
> Remove explicit deprecation messages

- CHANGELOG.md
- provider/resources.go
Related to: https://github.com/pulumi/pulumi-aws/issues/1299
Auto-naming rules derived from: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.CreateInstance.html#w483aac13c11c15b5:~:text=The%20DB%20cluster%20identifier%20has%20the,first%20character%20must%20be%20a%20letter.
> Fix autonaming for cluster_identifier

- CHANGELOG.md
- provider/resources.go
- sdk/dotnet/Rds/Cluster.cs
- sdk/dotnet/Rds/ClusterEndpoint.cs
- sdk/dotnet/Rds/ClusterInstance.cs
- sdk/dotnet/Rds/GetClusterSnapshot.cs
- sdk/go/aws/rds/cluster.go
- sdk/go/aws/rds/clusterEndpoint.go
- sdk/go/aws/rds/clusterInstance.go
- sdk/go/aws/rds/getClusterSnapshot.go
- sdk/nodejs/rds/cluster.ts
- sdk/nodejs/rds/clusterEndpoint.ts
- sdk/nodejs/rds/clusterInstance.ts
- sdk/nodejs/rds/getClusterSnapshot.ts
- sdk/python/pulumi_aws/rds/cluster.py
- sdk/python/pulumi_aws/rds/cluster_endpoint.py
- sdk/python/pulumi_aws/rds/cluster_instance.py
- sdk/python/pulumi_aws/rds/get_cluster_snapshot.py
I tested to make sure this isn't breaking for folks who might've made a cluster during the in-between versions by creating an rds cluster with v3.23.0 and then updating it using a locally built version after making this change. The cluster updates with no changes since the pulumi-autonaming is preserved  as an input property in state and therefore tf autonaming never comes up.
Fixes: https://github.com/pulumi/pulumi-aws/issues/1299
> Revert autonaming of db clusters

- CHANGELOG.md
- provider/resources.go
- sdk/dotnet/Config/Config.cs
- sdk/dotnet/Provider.cs
- sdk/go/aws/config/config.go
- sdk/go/aws/provider.go
- sdk/nodejs/config/vars.ts
- sdk/nodejs/provider.ts
- sdk/python/pulumi_aws/config/vars.py
- sdk/python/pulumi_aws/provider.py
Fixes: #873
* `skipCredentialsValidation` now defaults to `true`.
* `skipGetEc2Platforms` now defaults to `true`.
* `skipMetadataApiCheck` now defaults to `true`.
* `skipRegionValidation` now defaults to `true`.
It's important to note that this does not require the replacement of either default or named provider:
```
pulumi up --yes
Previewing update (dev)
View Live: https://app.pulumi.com/stack72/provider-change/dev/previews/cb4c2428-a6a2-40fe-aabc-814509e782a4
Type                     Name                 Plan
+   pulumi:pulumi:Stack      provider-change-dev  create
+   ├─ pulumi:providers:aws  my-provider          create
+   ├─ aws:s3:Bucket         stack72-bucket       create
+   └─ aws:s3:Bucket         stack72-bucket-2     create
Resources:
+ 4 to create
Updating (dev)
View Live: …
```
> Setting Provider defaults to remove slow calls to AWS STS and Metadata

- CHANGELOG.md
- examples/examples_nodejs_test.go
- examples/kms-alias/Pulumi.yaml
- examples/kms-alias/index.ts
- examples/kms-alias/package.json
- examples/kms-alias/tsconfig.json
- provider/resources.go
This commit adds custom options for autonaming of aws.kms.Alias
resources, in order to prepend "alias/" to the key name if it is not
already part of the logical resource name.
This permits autonaming of keys without diverging from established
logical naming patterns.
> Prepend 'alias/' to KMS Key Alias autoname

- CHANGELOG.md
- sdk/nodejs/iam/principals.ts
Adds Principal for AWS AppSync to nodejs SDK.
This is required when creating a DataSource for AppSync.
https://docs.aws.amazon.com/appsync/latest/devguide/attaching-a-data-source.html
> add app sync principal for nodejs sdk

- CHANGELOG.md
- provider/resources.go
- sdk/dotnet/ServiceCatalog/TagOptionResourceAssociation.cs
- sdk/go/aws/servicecatalog/tagOptionResourceAssociation.go
- sdk/nodejs/servicecatalog/tagOptionResourceAssociation.ts
- sdk/python/pulumi_aws/servicecatalog/tag_option_resource_association.py
Fixes: #1519
`resourceName` is a reserved name and this is causing a break in
our python sdk
> [breaking] Remap `aws.serviceCatalog.TagOptionResourceAssociation` `resourceName` to be `associatedResourceName`

- CHANGELOG.md
- provider/resources.go
- sdk/dotnet/ServiceCatalog/TagOptionResourceAssociation.cs
- sdk/go/aws/servicecatalog/tagOptionResourceAssociation.go
- sdk/nodejs/servicecatalog/tagOptionResourceAssociation.ts
- sdk/python/pulumi_aws/servicecatalog/tag_option_resource_association.py
Reverts pulumi/pulumi-aws#1520
> Revert "[breaking] Remap `aws.serviceCatalog.TagOptionResourceAssociation` `resourceName` to be `associatedResourceName`"

- .goreleaser.prerelease.yml
- .goreleaser.yml
- CHANGELOG.md
- Makefile
- provider/go.mod
- provider/go.sum
Fixes: #1553
We now pass:
```
User-Agent: APN/1.0 Pulumi/1.0 Pulumi-Aws/4.17.0-alpha.1629393364+0b9d696e.dirty (+https://www.pulumi.com) aws-sdk-go/1.40.20 (go1.16.4; darwin; amd64)
```
Rather than:
```
User-Agent: APN/1.0 Hashicorp/1.0 Terraform/1.0.5 (+https://terraform.io) aws-sdk-go/1.40.20 (go1.16.4; darwin; amd64)
```
> Updating AWS APN to pass pulumi not terraform

- CHANGELOG.md
- sdk/nodejs/dynamodb/dynamodbMixins.ts
- sdk/nodejs/sqs/sqsMixins.ts
Fixes: #1634
Fixes: #1642
- Add ability to set maximumBatchingWindowInSeconds to aws.sqs.QueueEventSubscription NodeJS SDK mixin
- Add the ability to set functionResponseTypes as part of aws.dynamodb.TableEventSubscription in NodeJS SDK
> Support updates to dynamodb and sqs NodeJS mixins for use in lambda.EventSourceMapping

- CHANGELOG.md
- provider/resources.go
- sdk/dotnet/Mq/Broker.cs
- sdk/go/aws/mq/broker.go
- sdk/nodejs/mq/broker.ts
- sdk/python/pulumi_aws/mq/broker.py
Fixes: #1686
Before:
```
Type                 Name                Plan       Info
+   pulumi:pulumi:Stack  test-mk-broker-dev  create
└─ aws:mq:Broker     test                           2 errors
Diagnostics:
aws:mq:Broker (test):
error: aws:mq/broker:Broker resource 'test' has a problem: Missing required argument: The argument "broker_name" is required, but no definition was found.. Examine values at 'Broker.BrokerName'.
error: aws:mq/broker:Broker resource 'test' has a problem: Invalid or unknown key. Examine values at 'Broker.BrokerName'.
```
After:
```
View Live: https://app.pulumi.com/stack72/test-mk-broker/dev/previews/98b3b496-659c-4949-9abd-777029c318e3
Type                 Name                Plan
+   pulumi:pulumi:Stack  test-mk-broker-dev  create
+   └─ aws:mq:Broker     test …
```
> Fix regression in management of aws.mq.Broker this was due to an incorrect mapping in the provider SchemaInfo

- Makefile
- sdk/dotnet/go.mod
- sdk/nodejs/go.mod
- sdk/python/go.mod
gopls complains at duplicate modules within the same workspace so make fake module names unique. This makes the project openable in VSCode and other editors with no custom settings.
> Avoid duplicate go module names

- provider/resources.go
- sdk/dotnet/Sns/SmsPreferences.cs
- sdk/go/aws/sns/smsPreferences.go
- sdk/nodejs/sns/smsPreferences.ts
- sdk/python/pulumi_aws/sns/sms_preferences.py
Fixes: #1808
We remove the string override to ensure we are passing an int
to the AWS API as expected
> aws.sns.SmsPreferences monthlySpendLimit should be an int

- provider/go.mod
- provider/go.sum
- provider/resources.go
- provider/shim/go.mod
- provider/shim/go.sum
- sdk/dotnet/CodeDeploy/DeploymentConfig.cs
- sdk/go/aws/codedeploy/deploymentConfig.go
- sdk/nodejs/codedeploy/deploymentConfig.ts
- sdk/python/pulumi_aws/codedeploy/deployment_config.py
- aws.codedeploy.DeploymentConfig can take advantage of autonaming
- Upgrade to v3.74.2 of the AWS Terraform Provider
Fixes: #1818
Fixes: #1807
> various fixes

- provider/go.mod
- provider/go.sum
- provider/shim/go.mod
- provider/shim/go.sum
Fixes: #1845
Before:
```
Diagnostics:
aws:lambda:Function (basicLambda):
error: aws:lambda/function:Function resource 'basicLambda' has a problem: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2], got dotnet6. Examine values at 'Function.Runtime'.
```
After:
```
▶ pulumi up
Updating (test-function-runtime6)
View Live: https://app.pulumi.com/stack72/lambda/test-function-runtime6/updates/1
Type                    Name                           Status
+   pulumi:pulumi:Stack     lambda-test-function-runtime6  created
+   ├─ aws:iam:Role …
```
> enable dotnet6 runtime for AWS Lambda Functions

- provider/resources.go
- sdk/dotnet/S3/BucketV2.cs
- sdk/go/aws/s3/bucketV2.go
- sdk/nodejs/s3/bucketV2.ts
- sdk/python/pulumi_aws/s3/bucket_v2.py
This will allow a user to be able to migrate from the old
type of bucket to the new type
> aws.s3.Bucket: Alias the legacy Bucket to the V2 Bucket

- sdk/nodejs/ecs/container.ts
`secretOptions` is silently passed through to the underlying logConfiguration anyways. See https://github.com/pulumi/pulumi-aws/issues/1345. This just adjusts the typings to support it.
> Add `secretOptions` to LogConfiguration

- sdk/nodejs/kinesis/kinesisMixins.ts
Per the guidelines here - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html
Similar to this PR - https://github.com/pulumi/pulumi-aws/pull/1644
> Support functionResponseTypes for Kinesis

- provider/go.mod
- provider/go.sum
- provider/resources.go
- provider/shim/go.mod
- provider/shim/go.sum
- sdk/dotnet/Eks/Cluster.cs
- sdk/dotnet/Eks/GetCluster.cs
- sdk/go/aws/eks/cluster.go
- sdk/go/aws/eks/getCluster.go
- sdk/go/aws/eks/pulumiTypes.go
- sdk/nodejs/eks/cluster.ts
- sdk/nodejs/eks/getCluster.ts
- sdk/python/pulumi_aws/eks/cluster.py
- sdk/python/pulumi_aws/eks/get_cluster.py
Fixes: #1892
As part of the major version upgrade, we introduced a regression where
certificate authority became a list. This meant that the parameter
name changed from certificateAuthority to certificateAuthorities
This broke the state when trying to get the certificate authority
for use in connecting to the cluster
We now have 2 parameters - the original certificateAuthority AND the
new certificateAuthorities
All existing state will continue to work as expected now
I expect to see this as a "breaking change" in the getCluster function as we broke that on the major version upgrade
> aws.eks.Cluster: Fix regression in certificateAuthority

- provider/go.mod
- provider/go.sum
- provider/resources.go
- provider/shim/go.mod
- provider/shim/go.sum
- sdk/dotnet/Eks/Cluster.cs
- sdk/dotnet/Eks/GetCluster.cs
- sdk/go/aws/eks/cluster.go
- sdk/go/aws/eks/getCluster.go
- sdk/go/aws/eks/pulumiTypes.go
- sdk/nodejs/eks/cluster.ts
- sdk/nodejs/eks/getCluster.ts
- sdk/python/pulumi_aws/eks/cluster.py
- sdk/python/pulumi_aws/eks/get_cluster.py
In #1896, we added a new backward compatible type for certificateAuthority
to ensure that it was available rather than being the new list
Unfortunately, this introduced a string and the old type for certificateauthority
was actually an object with a Data parameter inside it
This rectifies the issue
[![asciicast](https://asciinema.org/a/rdSykSbX5OTv3GD2fvUmEXXZv.svg)](https://asciinema.org/a/rdSykSbX5OTv3GD2fvUmEXXZv)
> aws.eks.cluster: Ensure that certificateAuthority is backward compatible

- provider/resources.go
- sdk/dotnet/Config/Config.cs
- sdk/dotnet/Provider.cs
- sdk/go/aws/config/config.go
- sdk/go/aws/provider.go
- sdk/nodejs/config/vars.ts
- sdk/nodejs/provider.ts
- sdk/python/pulumi_aws/config/vars.py
- sdk/python/pulumi_aws/provider.py
Fixes: #1906
When this is stored in state, a second run of Pulumi with a different
PROFILE name will fail
> Remove storing AWS_PROFILE in state

- provider/go.mod
- provider/go.sum
- provider/shim/go.mod
- provider/shim/go.sum
- sdk/dotnet/S3/BucketObject.cs
- sdk/go/aws/s3/bucketObject.go
- sdk/nodejs/s3/bucketObject.ts
- sdk/python/pulumi_aws/s3/bucket_object.py
Fixes: #1911
FixeS: #1910
These warnings were from upstream and not someething we care about
disclosing to the user
> aws.s3.BucketObject: Remove the Deprecation Warnings

- provider/resources.go
According to docs: https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html
`This name must be unique per region per account, can have a maximum of 32 characters, must contain only alphanumeric characters or hyphens, and must not begin or end with a hyphen.`
> Fix TargetGroup's autoname length

- provider/resources.go
We mark aws_ecr_credentials as having whitespace docs so that we can
upgrade the Bridge dependency automatically. (The new version of the
bridge will fail by default if docs are missing.)
> [internal] Mark empty docs for aws_ecr_credentials

- README.md
- provider/resources.go
- sdk/python/README.md
Fixes: #1995
We now ensure that the preConfigureCallback function is sensitive to
skipCredentialsValidation and skipMetadataApiCheck
If the user sets skipCredentialsValidation: true in their config
then we don't run any preConfigureCallback. It's an explicit operation
to skip the credentials check.
If the user is validating via the metadata api, then they will set
skipMetadataApiCheck: false in the configuration and we need to ensure
we set the correct imds confiuration before we try and authenticate
the user
> Change how preConfigureCallback happens to ensure Metadata API included

- examples/examples_nodejs_test.go
- provider/resources.go
- sdk/dotnet/Config/Config.cs
- sdk/dotnet/Provider.cs
- sdk/go/aws/config/config.go
- sdk/go/aws/provider.go
- sdk/nodejs/config/vars.ts
- sdk/nodejs/provider.ts
- sdk/python/pulumi_aws/config/vars.py
- sdk/python/pulumi_aws/provider.py
This will ensure we can work on a real fix for why #1995 is currently
broken while users can't set credentials files or PROFILE
> Setting skipCredentialsValidation by default

- provider/resources.go
- sdk/dotnet/Config/Config.cs
- sdk/dotnet/Provider.cs
- sdk/go/aws/config/config.go
- sdk/go/aws/provider.go
- sdk/nodejs/config/vars.ts
- sdk/nodejs/provider.ts
- sdk/python/pulumi_aws/config/vars.py
- sdk/python/pulumi_aws/provider.py
Fixes: #1995
**Currently the creds validation is broken:**
[![asciicast](https://asciinema.org/a/AgIZGKgVnFEejf2wKIegTECrm.svg)](https://asciinema.org/a/AgIZGKgVnFEejf2wKIegTECrm)
New code:
**With AWS_PROFILE:**
[![asciicast](https://asciinema.org/a/qSdDAZCtgnDWiCBH2MBG5cQ8I.svg)](https://asciinema.org/a/qSdDAZCtgnDWiCBH2MBG5cQ8I)
**With default creds:**
[![asciicast](https://asciinema.org/a/A4v7yF9VHq1Mr0hayfkabLNBm.svg)](https://asciinema.org/a/A4v7yF9VHq1Mr0hayfkabLNBm)
**With Environment Vars for AWS_ACCESS_KEY_ID && AWS_SECRET_ACCESS_KEY**
[![asciicast](https://asciinema.org/a/qB50n4onFLYQAwARCGhwVQVK7.svg)](https://asciinema.org/a/qB50n4onFLYQAwARCGhwVQVK7)
**Using an AWS AssumeRole:**
[![asciicast](https://asciinema.org/a/fvfbhZDzwYvWEM5NI72iIQzVC.svg)](https://asciinema.org/a/fvfbh …
> Ensure we validate credentials correctly

- provider/resources.go
part of #1968 
redirecting input from the provider to the CLI and back over GRP seems like a lot of work at the moment.
I was trying to optimize for power users double-clicking to pick up the entire command to copy and paste more effortlessly.
the output of the current PR looks as such
```
kdixler@kdixler-20xw004aus ~/Documents/aws-python % pulumi up
Previewing update (dev)
View Live: https://app.pulumi.com/dixler/aws-python/dev/previews/6ddacf00-ff5b-4d70-ac17-9f7191c173f6
Type                 Name            Plan       Info
+   pulumi:pulumi:Stack  aws-python-dev  create     
└─ aws:s3:Bucket     my-bucket                  1 error
Diagnostics:
aws:s3:Bucket (my-bucket):
error: unable to validate AWS credentials - see https://pulumi.io/install/aws.html for details on configuration
log in …
```
> improve error message to contain command to configure AWS credentials

- provider/resources.go
The current implementation of SGRule means that only description
can be changed. Everything else on the resource is ForceNew by
default
Unfortunately, when a SGRule changes, we try and create a new rule
before deleting the old one. We can't create 2 rules of the same
in a SG therefore, we get an error
This ensures we delete the rule first before creating the new one
> aws.ec2.SecurityGroupRule: Ensure DeleteBeforeReplace

- docs/resource/aws_acm_certificate_validation.examples.md
- provider/go.mod
- provider/go.sum
- provider/resources.go
- sdk/dotnet/Acm/CertificateValidation.cs
- sdk/go/aws/acm/certificateValidation.go
- sdk/java/src/main/java/com/pulumi/aws/acm/CertificateValidation.java
- sdk/nodejs/acm/certificateValidation.ts
- sdk/python/pulumi_aws/acm/certificate_validation.py
Fixes: #2064
Fixes: #2032
Fixes: #2029
Fixes: #https://github.com/pulumi/registry/issues/1224
> aws.acm.CertificateValidation: Refactor the API docs to work

- provider/resources.go
Fixes #2144.
I followed the pattern we use in pulumi-azure to surface the underlying error.
I am open to other suggestions but I feel at this point it is more helpful to the user to forward the error from TF or AWS.
A screenshot of the new error surfacing when `aws-region is not set:
Sample terminal output for an invalid role ARN, with identity details removed:
```
Diagnostics:
aws:ec2:VpcIpam (guin):
error: unable to validate AWS credentials. Details: IAM Role (xxxxxxxx/xxxx) cannot be assumed.
There are a number of possible causes of this - the most common are:
* The credentials used in order to assume the role are invalid
* The credentials do not have appropriate permission to assume the role
* The role ARN is not valid
Error: operation error STS: AssumeRole, https response error …
```
> Read in role ARN in preConfigure validation

- README.md
- provider/resources.go
- sdk/python/README.md
In order to ensure that the user doesn't need to add anything to
state to skip a credentials validation or to skip the metadata api
check, we now allow a user to set the value via environment variables.
The order of operations is that we check for provider configuration
first and if we can't find it, we check for the environment variable
Therefore, a person who wants to skip the credentials validation can
now set:
AWS_SKIP_CREDENTIALS_VALIDATION=true when running pulumi up
> preconfigureCallback: Allow Env Vars for Credentials Validation

- README.md
Fixed a link that shows `license as invalid` with a link that shows the `License version as well as the name of the License`. Check the file for more info.
> Fixed a bug in Readme

- provider/resources.go
Fix https://github.com/pulumi/pulumi-aws/issues/2208
> Set DeleteBeforeReplace option for iam.AccountAlias

- provider/go.mod
- provider/go.sum
- provider/shim/go.mod
- provider/shim/go.sum
- sdk/go/aws/rds/instance.go
- sdk/java/src/main/java/com/pulumi/aws/rds/Instance.java
- sdk/java/src/main/java/com/pulumi/aws/rds/InstanceArgs.java
- sdk/java/src/main/java/com/pulumi/aws/rds/inputs/InstanceState.java
- sdk/nodejs/rds/instance.ts
- sdk/python/pulumi_aws/rds/instance.py
Fixes #2203 
This just turns off the warning for now as either approach works for the time being. 
This patch is maintained in the upstream fork. This should be reverted once https://github.com/pulumi/pulumi/issues/9115 is fixed and we have a way of migrating existing resources to the new property without causing replacements.
> Remove deprecation of RDS Instance name

- provider/resources.go
- sdk/dotnet/Rds/Enums.cs
- sdk/go/aws/rds/pulumiEnums.go
- sdk/java/src/main/java/com/pulumi/aws/rds/enums/StorageType.java
- sdk/nodejs/types/enums/rds/index.ts
- sdk/python/pulumi_aws/rds/_enums.py
RDS supports gp3 storage types for multiple RDS configurations. Allow the selection of gp3 storage type.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html#Concepts.Storage.GeneralSSD
> Add support for gp3 storage in RDS

- examples/eventbus/Pulumi.yaml
- examples/eventbus/index.ts
- examples/eventbus/package.json
- examples/eventbus/tsconfig.json
- examples/examples_nodejs_test.go
- sdk/nodejs/cloudwatch/eventRuleMixins.ts
In cases where the EventRule specified an eventBus other than `default`, this was not being used correctly in the EventTarget.  We can just pass along the eventBusName from the rule to the target.
Fixes #1323.
> Fix eventBus support in EventRule#onEvent

- provider/resources.go
- sdk/dotnet/Config/Config.cs
- sdk/dotnet/Provider.cs
- sdk/go/aws/config/config.go
- sdk/go/aws/provider.go
- sdk/java/src/main/java/com/pulumi/aws/Config.java
- sdk/java/src/main/java/com/pulumi/aws/ProviderArgs.java
- sdk/nodejs/config/vars.ts
- sdk/nodejs/provider.ts
- sdk/python/pulumi_aws/config/__init__.pyi
- sdk/python/pulumi_aws/config/vars.py
- sdk/python/pulumi_aws/provider.py
Since the upstream provider deprecated this setting, all uses of this provider emit this warning on all operations:
```warning: provider config warning: With the retirement of EC2-Classic the skip_get_ec2_platforms attribute has been deprecated and will be removed in a future version.```
This PR removes the setting from provider configuration.
Tested locally via `replace github.com/pulumi/pulumi-aws/sdk/v5 => $HOME/pulumi/pulumi-aws/sdk` and observing the before/after change.
Fixes #2292
> Remove deprecated skip_get_ec2_platforms config

- .gitmodules
HTTPS is the standard at Pulumi and avoids setting up SSH keys in workflows.
> Configure pulumi/terraform-provider-aws submodule to use HTTPS like elsewhere

- .github/workflows/main.yml
- .github/workflows/master.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
Our release job uses goreleaser which was previously configured to timeout at 120m.  The build itself often takes 110m, which can easily slip over the 120m timeout threshold.  This bumps to 150m to cover the +-10% band and prevent the job from artificially failing.
> Updates timeout on goreleaser to 150m

- provider/resources.go
- Fix missing values in auth error messages coming from upstream
- Update link to Pulumi docs
- Shorten a bit
Before (note second line "for ..." and third line "see ..."):
```
error: unable to validate AWS credentials.
Details: no valid credential sources for  found.
Please see
for more information about providing credentials.
Error: <actual error>
Make sure you have:
• Set your AWS region, e.g. `pulumi config set aws:region us-west-2`
• Configured your AWS credentials as per https://pulumi.io/install/aws.html
You can also set these via cli using `aws configure`.
```
After:
```
error: unable to validate AWS credentials.
Details: no valid credential sources for Pulumi AWS Classic found.
Please see https://www.pulumi.com/registry/packages/aws/installation-configuration/
for more information …
```
> Improve auth error message

- .github/workflows/main.yml
- .github/workflows/master.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
The `publish` step has started failing with the error "no space left on device":
https://github.com/pulumi/pulumi-aws/actions/runs/4308251155/jobs/7528823156
The default runner has 7GB of disk space, and I hypothesise that space is taken up by the Go build cache -- including the AWS SDK, six times (arch x OS), ends up being a lot of object files. As a mitigation, we can use a larger runner instance, which will come with signficantly more disk space.
Fixes #2400
> Use larger GitHub Actions runner for publish step

- .github/workflows/main.yml
- .github/workflows/master.yml
- .github/workflows/nightly-test.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
- .github/workflows/update-bridge.yml
- .github/workflows/update-upstream-provider.yml
Hoping to improve CI turnaround times a bit by introducing Go build caching everywhere.
> Update setup-go to v4 with implicit build caching

- .github/workflows/main.yml
- .github/workflows/master.yml
- .github/workflows/nightly-test.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
- .github/workflows/update-bridge.yml
- .github/workflows/update-upstream-provider.yml
This is an unusual repository - go.sum changes all the time, while there are not so many parallel builds. This means that typically all PRs have cache misses because they edit some go.sum somewhere. It would be preferable to fetch the wrong build cache (and rewrite it in each PR), hoping some parts of it still speed up the build, than it is to accept a cache miss.
This PR relies on the fact that sdk/go.sum is fairly stable, and uses it as a key. This is less precise but might be preferable.
> Cache Go builds on sdk/go.sum

- .github/workflows/main.yml
- .github/workflows/master.yml
- .github/workflows/nightly-test.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
- .github/workflows/update-bridge.yml
- .github/workflows/update-upstream-provider.yml
- provider/go.mod
Upgrade CI to build and test on Go 1.20.x from Go 1.19.x.
> Use Go 1.20.x

- .github/workflows/master.yml
- .github/workflows/nightly-test.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
- .github/workflows/update-bridge.yml
- .github/workflows/update-upstream-provider.yml
Our GH Actions are constantly erroring out as the runner keep running out of disk space when running `make tfgen build_sdks`. Example failed run: https://github.com/pulumi/pulumi-aws/actions/runs/5261853128
This PR uses the [jlumbroso/free-disk-space@main](https://github.com/jlumbroso/free-disk-space) action to clear out disk space of unused binaries. This amounts to ~21GB of disk space.
> Add disk clearing step before building SDKs in GHA

- examples/bucket/index.ts
- sdk/nodejs/utils.ts
Every folder inside the AWS Node.js SDK that has a mixin was importing "../utils", which imports "./awsMixins" which itself was forcing import of "." which then goes back and tries to force import of everything.  There is no clear reason why forcing this root module import was ever necesary. Nothing that imports utils.ts depends on the side effects caused by "awsMixins", and the primary effect of adding the `sdk` getter onto the root module is only relevant if the end user loads that root module itself so they can access this property.
Also expands some existing test coverage to test this and use of `aws.sdk`, which is the related feature that could in principle be impacted by removing this forced side effect
Fixes #772.
> Avoid importing full root `@pulumi/aws` module

- provider/resources.go
- sdk/dotnet/Lambda/Enums.cs
- sdk/go/aws/lambda/pulumiEnums.go
- sdk/java/src/main/java/com/pulumi/aws/lambda/enums/Runtime.java
- sdk/nodejs/types/enums/lambda/index.ts
- sdk/python/pulumi_aws/lambda_/_enums.py
https://aws.amazon.com/blogs/compute/ruby-3-2-runtime-now-available-in-aws-lambda/
> Add support for ruby 3.2 runtime

- provider/resources.go
- sdk/dotnet/Lambda/Enums.cs
- sdk/go/aws/lambda/pulumiEnums.go
- sdk/java/src/main/java/com/pulumi/aws/lambda/enums/Runtime.java
- sdk/nodejs/types/enums/lambda/index.ts
- sdk/python/pulumi_aws/lambda_/_enums.py
> Add Python 3.11 as a supported runtime for Lambda

- provider/resources.go
- sdk/nodejs/package.json
We no longer use this since https://github.com/pulumi/pulumi-aws/pull/2584
Closes https://github.com/pulumi/pulumi-aws/issues/2656
> Remove aws-sdk npm dependency

- provider/go.mod
- provider/go.sum
bridge: v3.56.2
bridge/pf: v0.15.2
Propagates bugfixes, most importantly GetRawConfig() no longer panics.
> Bridge dependency updates

- .github/workflows/main.yml
- .github/workflows/master.yml
- .github/workflows/nightly-test.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
- .github/workflows/update-bridge.yml
- .github/workflows/update-upstream-provider.yml
- provider/resources.go
- Fix broken master build
- It appears that the tests broke on an ambient Pulumi CLI update
- This PR pins Pulumi CLI to a specific version to avoid this breakage in the future
- We need to follow through with automatically standing up upgrade PRs to keep up-to-date
-  pulumi/action-install-pulumi-cli is deprecated in favor of pulumi/actions, doing it here
> Pin Pulumi CLI

- provider/resources.go
- sdk/dotnet/Lambda/Enums.cs
- sdk/go/aws/lambda/pulumiEnums.go
- sdk/java/src/main/java/com/pulumi/aws/lambda/enums/Runtime.java
- sdk/nodejs/types/enums/lambda/index.ts
- sdk/python/pulumi_aws/lambda_/_enums.py
Add support for Java 17 runtime.
> Add Support for Java17 Runtime

- .github/workflows/master.yml
- .github/workflows/prerelease.yml
- .github/workflows/run-acceptance-tests.yml
- Makefile
Having VERSION_PREFIX set to 6.0.0 makes pulumictl compute 6.0.0 versions for releases even when trying to release 6.0.2-alpha.1, which is unfortunate. Removing VERSION_PREFIX makes pulumictl consult the recent tag history and start computing appropriate 6.1.x versions. I hope to follow up on this PR by releasing 6.0.2-alpha.2 and having that go through the release workflow.
Here's the build for the v6.0.2-alpha.1 tag that versions the artifact as 6.0.0, illustrating the problem: 
https://github.com/pulumi/pulumi-aws/actions/runs/5837637745/job/15834490164#step:9:87
> Remove VERSION_PREFIX

- examples/go.mod
- examples/provider_upgrade_test.go
I'm getting success replaying eks.Cluster and rds.Instance test logs in memory, but it needs a slightly more complicated algorithm. The way we do this is we replay Check, Diff in tandem. We borrow old unchecked inputs from the log, we pass them through the provider to get checked inputs, and then we modify the recorded Diff to have these checked inputs part of the call. This is more realistic I think to what the engine does.
```
=== RUN   TestProviderUpgradeQuick
provider_upgrade_test.go:331: Replayed Diff on urn:pulumi:p-it-antons-mac-resources-3a5a9fc3::resources::aws:iam/role:Role::ekscluster1role
provider_upgrade_test.go:331: Replayed Diff on urn:pulumi:p-it-antons-mac-resources-3a5a9fc3::resources::aws:ec2/vpc:Vpc::vpc1
provider_upgrade_test.go:331: Replayed Diff on …
```
> Enable quick replay of upgrade tests

- Makefile
This does the same thing that other bridged providers does: configure the upstream repository for use.
Fixes https://github.com/pulumi/ci-mgmt/issues/530
---
We plan to merge after v6.1.0 has released. We don't want to release before since we don't want to delay the release.
> Add a make 'upstream' target

- .github/workflows/main.yml
- .github/workflows/master.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
Under the new workflow files, this test is included whenever we run our other tests. Importantly, the post-test phase of the relevant workflows depend on this test running successfully. We can't skip the test (for example [during releases](https://github.com/pulumi/pulumi-aws/actions/runs/6032096288), since that blocks the post-test actions).
This PR reflects the changes made in https://github.com/pulumi/ci-mgmt/pull/538.
> Always run extra test

- .github/workflows/run-acceptance-tests.yml
- .gitignore
- Makefile
- codecov.yml
This adds basic code coverage for our provider binaries as exercised by our unit tests. An example of the comment produced by the tool occurs on this PR; the coverage report is informational only (will not block PR checks). 
Note: Since this only applies to unittests, we're not covering much here. The only unittests in this repo today are on the shim.
> Adding codecov to this repo

- examples/examples_test.go
- patches/0001-Add-TagsSchemaTrulyComputed-definition.patch
- patches/0002-Conns-user-agent.patch
- patches/0003-Add-S3-legacy-bucket-to-resources.patch
- patches/0004-Marks-SSE-Configuration-as-Computed-for-Legacy-S3-Bu.patch
- patches/0005-De-deprecate-bucket_object.patch
- patches/0006-Remove-lakeformation-catalog_resource-default.patch
- patches/0007-Workaround-SSM-Parameter-tier-bug.patch
- patches/0008-Add-EKS-cluster-default_addons_to_remove.patch
- patches/0009-Add-EKS-cluster-certificate_authorities-plural.patch
- patches/0010-Workaround-Autoscaling-launch_configuration-associat.patch
- patches/0011-Add-ECR-credentials_data_source.patch
- patches/0012-Add-custom-appautoscaling-examples.patch
- patches/0013-Add-dedicated_host-docs.patch
- patches/0014-Revert-WAF-schema-changes.patch
- patches/0015-Catch-cty-panic-in-new-resourceTopicSubscriptionCust.patch
- patches/0016-add-matchmaking-configuration-72.patch
- patches/0017-fix-Adding-back-in-removeAddons.patch
- patches/0018-Reverts-patches-to-S3BucketLegacy-and-GameLift.patch
- patches/0019-Revert-Update-endpointHashIPAddress.patch
- patches/0020-Fixup-eks-formatting.patch
- patches/0021-Fixup-gamelift-context.patch
- patches/0022-Change-default-descriptions-to-Managed-by-Pulumi.patch
- patches/0023-remove-required-elements-from-schema-and-fix-tests-7.patch
- patches/0024-Temp-remove-cognito_identity_pool_roles_attachment-e.patch
- patches/0025-Fix-elbv2-target-group-read.patch
- patches/0026-Fix-spurrious-json-diff-for-redrive_policy.patch
- patches/0027-Provide-context-to-conns.patch
- patches/0028-Match-the-tags-behavior-of-other-resources.patch
- patches/0029-move-shim-logic-to-upstream-as-a-patch.patch
Fixes #2796
Upstream has added a depreciation warning to `aws_s3_bucket_object`, deprecating it in favor of `aws_s3_object` (`aws:s3/bucketObjectV2:BucketObjectV2`).
This PR is the quick fix, simply removing the message.
Long term, we should come up with a plan to right upstream against s3:
1. Deprecate `aws:s3/bucketObject:BucketObject` and `aws:s3/bucketObjectV2:BucketObjectV2` in favor of `aws:s3/object:Object`.
If we can confirm it is safe to use `aws_s3_object` with our `aws:s3/bucket:Bucket`, we can hard alias `aws:s3/bucketObjectV2:BucketObjectV2` to `aws:s3/object:Object` and restore the deprecation warnings. If not, we will need to wait until we can resolve (2) to resolve (1).
2. Find a migration path back to where `aws:s3/bucket:Bucket` is the preferred bucket to use (mirroring …
> Remove deprecation warning on `aws_s3_bucket_object`

- examples/go.mod
- examples/go.sum
- provider/go.mod
- provider/go.sum
Fixes https://github.com/pulumi/pulumi-aws/issues/2812
Fixes https://github.com/pulumi/pulumi-aws/issues/2806
We could not use upgrade-provider for this operation because there was a conflict between upstream changes editing a go.sum and one of our patches doing the same, so the patch did not apply cleanly. Resolved manually by rebating upstream and rebuilding the patch set.
The new upstream version targeted here is 5.17.0.
On top of the upstream upgrade, this PR updates dependencies from pulumi-terraform-bridge to propagate bugfixes:
- github.com/pulumi/pulumi-terraform-bridge/pf v0.16.1
- github.com/pulumi/pulumi-terraform-bridge/v3 v3.60.0
> Upgrade upstream to v5.17.0

- provider/diag.go
- provider/diag_test.go
- provider/resources.go
A tactical improvement for https://github.com/pulumi/pulumi-aws/issues/2285 to avoid Go pointers leaking into error messages.
Before:
> unable to validate AWS credentials.
Details: [{0x14009acaee0}]
Make sure you have set your AWS region, e.g. `pulumi config set aws:region us-west-2`.
After:
> unable to validate AWS credentials.
Details: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, failed to resolve service endpoint, endpoint rule error, Invalid Configuration: Missing Region
Make sure you have set your AWS region, e.g. `pulumi config set aws:region us-west-2`.
> Format diagnostics from GetAwsConfig as readable strings instead of %v format dump

- provider/resources.go
Part of https://github.com/pulumi/marketing/issues/816
This PR adds some text to current text emitted when a user hits a credentials to let them know about ESC and that they can configure their AWS creds with ESC. When I was testing this locally I noticed the error emitted twice (same with a warning about using the aws plugin from my path) so not sure if that is expected with local dev. 
Example output:
> Add text to inform users about ESC on creds error

- examples/bucket-yaml/Pulumi.yaml
- examples/diagnostic_test.go
- provider/resources.go
This should address the error duplication reported in https://github.com/pulumi/pulumi-aws/issues/2285 as suggested by @t0yv0.
We now have a global counter which guard the credentials check and makes sure we only run it once.
For testing, I ran a few programs both with and without errors and it does seem to do the right thing.
```
Previewing update (dedev)
View in Browser (Ctrl+O): https://app.pulumi.com/venelin-pulumi-corp/aws_bucket_go/dedev/previews/88831526-f63f-42f2-98d9-957fbea78fc0
Type                     Name                 Plan     Info
pulumi:pulumi:Stack      aws_bucket_go-dedev           4 war
└─ pulumi:providers:aws  default                       1 err
Diagnostics:
pulumi:providers:aws (default):
error: rpc error: code = Unknown desc = unable to validate AWS credentials. …
```
> Run credentials validation only once

- examples/examples_go_test.go
Generic CI failures with "The maximum number of VPCs has been reached”  point to large number of VPCs.
```
// Destroy on cleanup defers stack destruction until the test cleanup step, rather than after
// program test execution. This is useful for more realistic stack reference testing, allowing one
// project and stack to be stood up and a second to be run before the first is destroyed.
//
// Implies NoParallel because we expect that another caller to ProgramTest will set that
```
One problem here is that a matrix-style test that tries 100 random combinations of VPC+Bucket should not be setting DestroyOnCleanup.
> Do not set DestroyOnCleanup for matrix tests

- patches/0031-Optimize-startup-performance.patch
Zooming in a lot on AWS Provider startup costs, noticing a recurring pattern. In SDKv2 we have schema.Resource that has Schema of type map but also SchemaFunc  The latter is designed specifically to defer / lazy instantiate schemas that are big. It looks like in AWS QuickSight and some other very large schemas make use of this. However over time transformations baked into upstream providers and our own bridge added up to a lot of passes that force-call these SchemaFunc() on startup, even if you don't use QuickSight. When done sequentially it all adds up. Moreover since there's no true laziness we end up paying the QuickSight etc cost multiple times.
This change does the following to avoid `SchemaFunc()` calls:
- turn off upstream tags check - this seems to be a validation-only measure, …
> Optimize startup performance

- examples/examples_nodejs_test.go
In preparation for pulumi/pulumi#14695 which will cause such tests to break.
> Use correct EditDirs in test

- provider/resources.go
- provider/resources_test.go
- Add `assumeRoleWithWebIdentity` to creds validation #2252
- Add most missing properties to assumeRole credentials check
- Add duration to supported assumeRole properties
Resolves ##2252
The supported properties of both `assumeRole` and `assumeRoleWithWebIdentity` should now match [the ones documented in the registry](https://www.pulumi.com/registry/packages/aws/installation-configuration/#configuration-options).
The remaining exception is `tags` where I wasn't sure about the correct conversion from `PropertyMap` to Go `map`.
I have an e2e test for `assumeRoleWithWebIdentity` in progress as part of #3074 but wanted to get this change out there.
> Add assume role with web identity, expand assume role properties in creds validation

- examples/go.mod
- examples/go.sum
- provider/go.mod
- provider/go.sum
- provider/provider_nodejs_test.go
- provider/test-programs/regress-3094/.gitignore
- provider/test-programs/regress-3094/Pulumi.yaml
- provider/test-programs/regress-3094/index.ts
- provider/test-programs/regress-3094/package.json
- provider/test-programs/regress-3094/tsconfig.json
Fixes #3094. With these changes I can preview and up the repro program.
The actual fix is in https://github.com/pulumi/pulumi-terraform-bridge/pull/1558
All bridge changes (to confirm) - this is the only change: https://github.com/pulumi/pulumi-terraform-bridge/compare/v3.67.0...538570c1932f59b78ee6a2f0843ce6c04976131e
> Fix 3094: preview when provisioning SecurityGroup with unknown ingress

- provider/cmd/pulumi-resource-aws/main.go
- provider/cmd/pulumi-tfgen-aws/main.go
- provider/fast_test.go
- provider/resources.go
At this point bridge-metadata.json is a compile-time only concern as it is not needed at runtime at all. This PR makes the change obvious and stops embedding it. This should help the binary size a bit, possibly to the tune of 30MB (uncompressed):
31M    provider/cmd/pulumi-resource-aws/bridge-metadata.json
88K    provider/cmd/pulumi-resource-aws/runtime-bridge-metadata.json
Only runtime-bridge-metadata.json is currently needed.
> Stop embedding bridge-metadata.json

- .ci-mgmt.yaml
- .github/workflows/master.yml
- .github/workflows/nightly-test.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/resync-build.yml
- .github/workflows/run-acceptance-tests.yml
Before this change, we used an outdated Pulumi CLI version to test the provider against. With this change we start using the latest 3.x release like most other bridged providers. While it would be my preference to have it pinned and automatically updating via PRs to move toward [Hermetic Builds](https://github.com/pulumi/ci-mgmt/issues/738) that's more work and for now this change is a quick improvement.
> Unpin pulumi cli 3

- examples/examples_dotnet_test.go
- examples/examples_nodejs_test.go
- examples/examples_py_test.go
- examples/examples_test.go
- examples/main_test.go
Prior to this change, all example-based acceptance tests inherited a relaxed configuration.
```go
return integration.ProgramTestOptions{
ExpectRefreshChanges: true,
SkipRefresh:          true,
Quick:                true,
}
```
This was masking issues with unexpected diffs during `refresh` and any possible regressions as there provider evolves. After the change, only the test that need it are configured with these relaxed options and the code is cross-correlated to root cause issues where appropriate.
> Make integration tests stricter

- examples/webserver-cs/Program.cs
- examples/webserver-go/main.go
Looks like amazon linux 1 reached end of life https://aws.amazon.com/blogs/aws/update-on-amazon-linux-ami-end-of-life/ 
They probably removed the amis from search results.
This PR fixes the examples to use amazon linux 2
> Fix failing tests because of missing amazon linux 1 AMI

- provider/resources.go
- sdk/nodejs/package.json
It looks like read-package-tree is vestigial, and it is deprecated, so we can remove it.
Fixes https://github.com/pulumi/pulumi-aws/issues/3212
> Validate if read-package-tree is necessary

- examples/examples_go_test.go
- examples/tags-combinations-go/main.go
- examples/tags-combinations-go/step1/main.go
Nothing that the TestRandomTagsCombinationsGo test periodically flakes up, as in https://github.com/pulumi/pulumi-aws/pull/3292  on testing VPC resources. I've not established the root cause but it appears to be that the VPCs allocated by independent test instances collide. This is probably just not a good resource to test tag correctness on and I think we're not losing much coverage by simply removing it. Buckets tests still test the SDKv2 based resources.
> Remove VPC from tags test matrix

- examples/examples_nodejs_test.go
- provider/resources.go
An experiment to see if PlanResourceChange can substitute for CtyInstanceState while still handling wafv2_web_acl resource correctly. See https://github.com/pulumi/pulumi-aws/issues/3361
> Swap CtyInstanceState with PlanResourceChange flag

- examples/go.mod
- examples/go.sum
Update the plugin sdk under `examples/` to match the one in the rest of the repo.
This one got missed in https://github.com/pulumi/pulumi-aws/pull/3370 and https://github.com/pulumi/pulumi-aws/pull/3377 due to https://github.com/pulumi/upgrade-provider/issues/246.
> Update plugin sdk replace in examples

- .ci-mgmt.yaml
- .github/workflows/check-upstream-upgrade.yml
- .github/workflows/license.yml
- .github/workflows/lint.yml
- .github/workflows/master.yml
- .github/workflows/nightly-test.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/resync-build.yml
- .github/workflows/run-acceptance-tests.yml
- scripts/upstream.sh
Needed for https://github.com/pulumi/ci-mgmt/issues/772 after https://github.com/pulumi/ci-mgmt/pull/818
Workflow updates otherwise fail: https://github.com/pulumi/pulumi-aws/pull/3430 because of a mismatch in upload/download artifact versions.
> Update ci-mgmt.yaml config to match ci-mgmt actions

- examples/examples_nodejs_test.go
- examples/role-inline-policy-auto-name/Pulumi.yaml
- examples/role-inline-policy-auto-name/README.md
- examples/role-inline-policy-auto-name/index.ts
- examples/role-inline-policy-auto-name/package.json
- examples/role-inline-policy-auto-name/tsconfig.json
- provider/resources.go
- sdk/nodejs/types/output.ts
In order to create an `inline_policy` on a role, both the `policy` and the `name` fields are required. If only one is provided then the policy will not be created (and no error will be thrown). Both properties must be optional though to allow providing empty values, i.e.
```ts
inlinePolicies: []
// or
inlinePolicies: [{}]
```
This PR sets the `name` property to be auto named and adds a transform on `inline_policy` to only create policies if a `policy` is provided.
fixes #1949
> fix: role inline policies fail to create without a policy name

- .ci-mgmt.yaml
- .github/workflows/master.yml
- .github/workflows/nightly-test.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
This pull request adds the `provider/` unit tests as a separate job via `.ci-mgmt.yaml` ExtraTests config.
It only runs python and nodejs matrix, as there are currently no other unit tests enabled that need other languages. I'm happy to adjust this as necessary.
This refactor is meant to address the AWS credentials timeout that causes #3637.
> run unit tests in separate job

- provider/resources.go
- sdk/dotnet/Ec2/NetworkAcl.cs
- sdk/dotnet/Ec2/SecurityGroup.cs
- sdk/go/aws/ec2/networkAcl.go
- sdk/go/aws/ec2/securityGroup.go
- sdk/java/src/main/java/com/pulumi/aws/ec2/NetworkAcl.java
- sdk/java/src/main/java/com/pulumi/aws/ec2/NetworkAclArgs.java
- sdk/java/src/main/java/com/pulumi/aws/ec2/SecurityGroup.java
- sdk/java/src/main/java/com/pulumi/aws/ec2/SecurityGroupArgs.java
- sdk/java/src/main/java/com/pulumi/aws/ec2/inputs/NetworkAclState.java
- sdk/java/src/main/java/com/pulumi/aws/ec2/inputs/SecurityGroupState.java
- sdk/nodejs/ec2/networkAcl.ts
- sdk/nodejs/ec2/securityGroup.ts
- sdk/python/pulumi_aws/ec2/network_acl.py
- sdk/python/pulumi_aws/ec2/security_group.py
Marks the `ingress` and `egress` properties of `ec2.SecurityGroup` as deprecated, and emits a warning at deployment time.  Same for `ec2.NetworkAcl`. It is recommended that the standalone "rule" resources be used instead.
The output resembles:
```
Diagnostics:
aws:ec2:SecurityGroup (clusterSecurityGroup):
warning: Use of inline rules is discouraged as they cannot be used in conjunction with any Security Group Rule resources. Doing so will cause a conflict and may overwrite rules.
```
Closes https://github.com/pulumi/pulumi-eks/issues/1031
> Deprecation: inline rules for SecurityGroup and NetworkAcl resources

- sdk/nodejs/iam/principals.ts
`eks.amazonaws.com` service principal seems to be missing
https://docs.aws.amazon.com/eks/latest/userguide/using-service-linked-roles-eks.html#service-linked-role-permissions-eks
> Add EKS service principal for Node.js SDK

- .ci-mgmt.yaml
- .github/workflows/master.yml
- .github/workflows/nightly-test.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
- Makefile
Instead of https://github.com/pulumi/pulumi-aws/pull/3744
It looks like simply reverting the change that caused us being unable to release hits disk space limits. 
Trying this change instead that avoids skipping the job so that releases are not skipped.
As part of this,  I ran `make ci-mgmt` which also inherited latest ci-mgmt changes.
> Fix release.yml

- examples/examples_go_test.go
- examples/tags-combinations-go/main.go
- examples/tags-combinations-go/step1/main.go
TestRandomTagsComabinationsGo periodically flakes up on failing to retrieve tags from AWS. This small change should add a retry to hopefully make it more robust. 
Fixes https://github.com/pulumi/pulumi-aws/issues/3403
> Retry for all tag fetching

- examples/examples_go_test.go
These tests continue to flake up in CI, and saldy I don't have a precise repro but I assume this has to do with eventual consistency of tagging data. Increasing timeout/retry. I restarted this job twice 🤞
> Higher timeout for Go test

- provider/resources.go
- sdk/dotnet/Ec2/NetworkAcl.cs
- sdk/dotnet/Ec2/SecurityGroup.cs
- sdk/go/aws/ec2/networkAcl.go
- sdk/go/aws/ec2/securityGroup.go
- sdk/java/src/main/java/com/pulumi/aws/ec2/NetworkAcl.java
- sdk/java/src/main/java/com/pulumi/aws/ec2/NetworkAclArgs.java
- sdk/java/src/main/java/com/pulumi/aws/ec2/SecurityGroup.java
- sdk/java/src/main/java/com/pulumi/aws/ec2/SecurityGroupArgs.java
- sdk/java/src/main/java/com/pulumi/aws/ec2/inputs/NetworkAclState.java
- sdk/java/src/main/java/com/pulumi/aws/ec2/inputs/SecurityGroupState.java
- sdk/nodejs/ec2/networkAcl.ts
- sdk/nodejs/ec2/securityGroup.ts
- sdk/python/pulumi_aws/ec2/network_acl.py
- sdk/python/pulumi_aws/ec2/security_group.py
This reverts commit 8fc4907dee19c2b85b6a589e626cbd764b9f45ab from https://github.com/pulumi/pulumi-aws/pull/3729
The warning message is considered too noisy for this sort of issue.
> Revert "Deprecation: inline rules for SecurityGroup and NetworkAcl resources"

- examples/kms-alias/index.ts
The test is creating a KMS key alias with a static name. When multiple
instances of this test are running in the same AWS account and region they'll race
and occasionally fail because the alias already exists.
This changes the key alias to use a name prefix to guarantee uniqueness.
This fixes: https://github.com/pulumi/pulumi-aws/issues/3817
> Fix flaky test TestAccKmsAliasTs

- examples/codebuild-project-py/__main__.py
AWS started setting an environment variable by default to auto discover reports (CODEBUILD_CONFIG_AUTO_DISCOVER) when creating CodeBuild projects.
This led to `pulumi preview` showing a diff after the initial deployment.
This change will fix the test, but the in behavior  from AWS will lead to users ending up with a drift when creating CodeBuild projects until they re-run `pulumi up` once.
This fixes https://github.com/pulumi/pulumi-aws/issues/3839
> Add CODEBUILD_CONFIG_AUTO_DISCOVER environment variable of CodeBuild example

- patches/0054-Revert-r-aws_db_proxy-Change-auth-from-TypeList-to-T.patch
In 0054-Revert-r-aws_db_proxy-Change-auth-from-TypeList-to-T patch we reverted an upstream change to avoid triggering a panic in Pulumi. The change moved rds.Proxy auths parameter from a List to a Set type. Unfortunately it looks like we neglected to remove the Set cutomizer that is not a valid customizer for list-typed properties. The resulting schema no longer passes InternalValidate which the new bridge release will run at make tfgen time, thus blocking the bridge upgrade.
This should unblock the bridge update.
> Fix 0054 patch to pass schema checks

- patches/0055-Fix-panic-in-aws_directory_service_directory-Read.patch
Fixes https://github.com/pulumi/pulumi-aws/issues/1152
Since it is difficult to repro at integration level, adding a unit test instead.
> Patch aws_directory_service_directory Read to avoid a panic

- provider/configure_test.go
- provider/resources.go
- sdk/dotnet/Provider.cs
- sdk/go/aws/provider.go
- sdk/java/src/main/java/com/pulumi/aws/Provider.java
- sdk/nodejs/provider.ts
- sdk/python/pulumi_aws/provider.py
This makes sure that any values passed to these provider configuration options are stored encrypted in the state file.
Fixes https://github.com/pulumi/pulumi-aws/issues/2447
> Marks accessKey, secretKey and token options as Secret

- examples/go.mod
- examples/go.sum
- provider/go.mod
- provider/go.sum
This is a quick fix to address customer issues outlined in https://github.com/pulumi/pulumi-terraform-bridge/issues/1940.
While we develop a more complete fix for the above issue, this will unblock customers and enable them to upgrade.
> Pin to bridge at c0c57794d7bbf33f84620e4532d7e097abab3248

- provider/provider_nodejs_test.go
- provider/test-programs/ec2-string-for-int/.gitignore
- provider/test-programs/ec2-string-for-int/Pulumi.yaml
- provider/test-programs/ec2-string-for-int/index.ts
- provider/test-programs/ec2-string-for-int/package.json
- provider/test-programs/ec2-string-for-int/tsconfig.json
This adds a program which uses a string for an int property.
This reproduces the issue seen in https://github.com/pulumi/pulumi-terraform-bridge/issues/1940
> AWS Attribute must be whole number regression test

- examples/examples_go_test.go
- patches/0038-Restore-legacy-bucket.patch
- provider/provider_test.go
- provider/provider_yaml_test.go
- provider/test-programs/regress-3674/Pulumi.yaml
Make sure that `pulumi refresh` detects changes to bucket tagging.
The implementation restores aws_s3_legacy_bucket resource participation in the generic tags interceptor.
Fixes #3674
> Fix aws.s3.Bucket tag drift detection

- provider/provider_python_test.go
The test flaked sometimes because it ran into the timeout.
The regression this test fixes had a wait time of hours, so changing the timeout to 6 minutes won't change the effectiveness of the regression test.
Fixes https://github.com/pulumi/pulumi-aws/issues/3945
> Increase timeout for TestRegress3196 test

- examples/examples_nodejs_test.go
- provider/resources.go
WAFv2 RuleGroups used to have a perma diff for the rules property.
Enrolling the resource in PlanResourceChange fixes that.
Fixes https://github.com/pulumi/pulumi-aws/issues/3306, https://github.com/pulumi/pulumi-aws/issues/3880, https://github.com/pulumi/pulumi-aws/issues/3190, https://github.com/pulumi/pulumi-aws/issues/3454
> Enroll aws_wafv2_rule_group in PlanResourceChange

- examples/webserver-comp/index.ts
- examples/webserver-comp/webserver.ts
The TestAccWebserverComp still occasionally flaked after upgrading the AMI. This changes the instances to a newer generation and changes the `nano` instance to a `small` to ensure the long boot times aren't caused by running out of CPU credits
Fixes: https://github.com/pulumi/pulumi-aws/issues/3903
> Upgrade instances for TestAccWebserverComp test

- provider/configure_test.go
- provider/provider_yaml_test.go
- provider/resources.go
- provider/test-programs/imds-auth/imds-v2/Pulumi.yaml
- provider/test-programs/imds-auth/imds-v2/remote-program/Pulumi.yaml
- sdk/dotnet/Config/Config.cs
- sdk/dotnet/Provider.cs
- sdk/go/aws/config/config.go
- sdk/go/aws/provider.go
- sdk/java/src/main/java/com/pulumi/aws/Config.java
- sdk/java/src/main/java/com/pulumi/aws/ProviderArgs.java
- sdk/nodejs/config/vars.ts
- sdk/nodejs/provider.ts
- sdk/python/pulumi_aws/config/__init__.pyi
- sdk/python/pulumi_aws/config/vars.py
- sdk/python/pulumi_aws/provider.py
This PR explores reverting the default `aws:skipMetadataApiCheck=false` setting to enable the provider to be able to seamlessly authenticate against an IMDS(v2) endpoints in the AWS environment. It appears that doing so no longer slows down the provider startup time perceptibly.  The way I tested the speed delta was by measuring local empty preview of an AWS s3 Bucket using AWS_PROFILE authentication with local <-> us-east-1 there is no perceptible difference.
Fixes: https://github.com/pulumi/pulumi-aws/issues/1692
An integration test is added that exercises `pulumi preview` on an EC2 instance with IMDSv2 and asserts that the provider can authenticate successfully. 
Background:
- https://github.com/pulumi/pulumi-aws/issues/873
- https://github.com/pulumi/pulumi-aws/pull/1288
> Do not skip metadata API check by default

- examples/go.mod
- examples/go.sum
This matches the main go.mod as well as the bridge replace.
The outdated replace was causing build failures with go.work files containing the bridge
> Update examples plugin sdk replace

- README.md
- sdk/python/README.md
Since https://github.com/pulumi/pulumi-aws/issues/1692 the provider no longer treats skipMetadataApiCheck specially but matches the behavior from Terraform upstream where this check is enabled unless the configuration value is explicitly set.
> Fix README for skipMetadataApiCheck

- provider/provider_nodejs_test.go
- provider/resources.go
- provider/test-programs/changing-region/.gitignore
- provider/test-programs/changing-region/Pulumi.yaml
- provider/test-programs/changing-region/index.ts
- provider/test-programs/changing-region/package.json
- provider/test-programs/changing-region/tsconfig.json
Enable `pulumi up` to do the right thing when AWS region changes in the program. It will now execute a cascading replace plan for all resources associated with a provider to delete resources in the old region and re-provision them in the new desired region.
Fixes https://github.com/pulumi/pulumi-aws/issues/3777 https://github.com/pulumi/pulumi-aws/issues/879
> Replace resources when the AWS region changes

- provider/resources.go
Fixes https://github.com/pulumi/pulumi-aws/issues/4008
The TF bridge currently requires a notion of ID for resources based on the Plugin Framework. Before these change the following resource used to panic, now they provision correctly:
- aws_lambda_runtime_management_config
- aws_datazone_environment_blueprint_configuration
- aws_vpc_endpoint_service_private_dns_verification
- aws_vpc_endpoint_private_dns
> Add ComputedID for resources that need it

- provider/pkg/batch/compute_environment.go
- provider/pkg/batch/compute_environment_test.go
- provider/provider_nodejs_test.go
- provider/provider_test.go
- provider/resources.go
Although the upstream schema of batch.ComputeEnvironment did not change between v5 and v6 of pulumi-aws, the Pulumi schema did, and computeResources.ec2Configuration is now an array. Prior to this change pulumi-aws v6 was not able to read the states written by the v5 of the provider correctly, if those states did involve a non-nil  computeResources.ec2Configuration.
In some of the recent bridge work this also interacted poorly with the new PlanResourceChange machinery causing panics. 
The change makes the provider automatically apply `x -> [x]` conversions to computeResources.ec2Configuration state.
Fixes #4015
> Fix migrating batch.ComputeEnvironment from v5 to v6 of the provider

- provider/doc_edits.go
- sdk/dotnet/Ecs/Service.cs
- sdk/go/aws/ecs/service.go
- sdk/java/src/main/java/com/pulumi/aws/ecs/Service.java
- sdk/java/src/main/java/com/pulumi/aws/ecs/ServiceArgs.java
- sdk/java/src/main/java/com/pulumi/aws/ecs/inputs/ServiceState.java
- sdk/nodejs/ecs/service.ts
- sdk/python/pulumi_aws/ecs/service.py
There is a docs example that is being dropped due to it including a `plantimestamp()` function which cannot be converted.
This PR puts the function within a string so that it does not attempt to convert it. I'm open to alternatives if anyone thinks there is something better to replace it with.
closes #2266, re https://github.com/pulumi/pulumi-converter-terraform/issues/140
> docs: correctly handle `plantimestamp()` function in docs

- .ci-mgmt.yaml
- .github/workflows/master.yml
- .github/workflows/prerelease.yml
- .github/workflows/prerequisites.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
Broken into 3 smaller commits for review.
Prerequisites does not run in a matrix, so there's no need to check for dotnet.
Removes the need to install dotnet for a second time.
- Set version for consistency with other jobs even though we likely won't use it.
- We're not running anything from the scripts repo in these test jobs. The only previous use of the scripts was for working tree clean checks, which we only perform during the build_sdk step, and should now use the `pulumi/git-status-check-action@v1` action for instead.
- Remove unshallow clone as we no longer need to fetch all tags to calculate the version via pulumictl.
> Simplify CI hooks

- .ci-mgmt.yaml
- .github/workflows/master.yml
- .github/workflows/nightly-test.yml
- .github/workflows/prerelease.yml
- .github/workflows/prerequisites.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
1. [Use built-in freeDiskSpace options instead of hooks](https://github.com/pulumi/pulumi-aws/pull/4061/commits/2c62884d93d8ec0652e44963b4ba483ff3afda7d)
- This runs the cleaning at the beginning of the job, avoiding deleting the tools we've just installed.
2. [Use new setup-tools action](https://github.com/pulumi/pulumi-aws/pull/4061/commits/1548cf853b774abd6ee4b1937b455257c445e2ab)
- Reduce duplication and ensure we're using a consistent version between jobs. 
- The tool versions are currently hard-coded and this removes that hard-coding so they're automatically upgraded.
> Simplify custom CI

- provider/cmd/pulumi-tfgen-aws/main.go
- provider/resources.go
This bypasses the need to call `shim.SchemaMap.Set` which has been removed in the latest version of the bridge. Since `"name"` is *never* witnessed by the underlying provider, it should not matter that the provider doesn't have the phony "name" field in it's map anymore.
Fixes https://github.com/pulumi/pulumi-terraform-bridge/issues/2101
> Directly inject `aws:rds:Instance.name` into the schema

- provider/provider_nodejs_test.go
- provider/provider_test.go
- provider/resources.go
- provider/test-programs/regress-4128/Pulumi.yaml
- provider/test-programs/regress-4128/index.ts
- provider/test-programs/regress-4128/package.json
- provider/test-programs/regress-4128/tsconfig.json
In #4083 we removed two patches fixing panics for `Listener` and `ListenerRule` resources and instead enrolled the resources in `PlanResourceChange`.
The ListenerRule (`lb.ListenerRule` and `alb.ListenerRule`) resources were missed to be enrolled in `PlanResourceChange`, which caused the original panic to surface again.
This change enrolls the ListenerRule resources in PlanResourceChange and adds a regression test covering those resources.
fixes #4128
> Fix ListenerRule panic if no forward parameter is missing in defaultActions

- patches/0061-Normalize-ecs.TaskDefinition-containerDefinitions-he.patch
- provider/diff_test.go
- provider/provider_test.go
Fixes #1738 
Fixes #1985
containerDefinitions expects a raw JSON which may lead to spurious diff on insignificant changes. The was pre-existing code for normalizing environment variable order and default values. This code is patched to extend it to handle normalizing the default value of healthCheck.timeout=5.
> Extend ecs.TaskDefinition containerDefinitions normalization

- examples/examples_nodejs_test.go
- examples/examples_test.go
- examples/regress-4011/index.ts
- examples/regress-4011/step1/index.ts
The test for regress-4011 is using a static name because it needs to import a created resource. This can clash with other parallel test runs.
To fix it I added some randomness to the name.
> Fix flake in regress-4011 test

- examples/regress-2868/index.ts
Some changes in the AWS cloud invalidated TestRegress2868:
https://github.com/pulumi/pulumi-aws/issues/4158
This change works around the problem to continue using TestRegress2868 for its original purposes (see #2868).
Fixes https://github.com/pulumi/pulumi-aws/issues/4152
> Adjust TestRegress2868 to ignore birthdate drift

- examples/go.mod
- provider/go.mod
- sdk/go.mod
Fixes https://github.com/pulumi/pulumi-aws/issues/4163
Upgrades minimally required Go versions to those unaffected by CVE-2024-24791.
> fix: CVE-2024-24791

- examples/regress-2555/index.ts
- examples/regress-2555/step1/index.ts
This test has been failing recently due to a resource with the same name
already existing. I think we have been running into a race condition
between different jobs.
Remove the hardcoded name.
> chore: fix flaky test

- provider/resources.go
- sdk/dotnet/GameLift/MatchmakingConfiguration.cs
- sdk/dotnet/GameLift/MatchmakingRuleSet.cs
- sdk/go/aws/gamelift/matchmakingConfiguration.go
- sdk/go/aws/gamelift/matchmakingRuleSet.go
- sdk/java/src/main/java/com/pulumi/aws/gamelift/MatchmakingConfiguration.java
- sdk/java/src/main/java/com/pulumi/aws/gamelift/MatchmakingRuleSet.java
- sdk/nodejs/gamelift/matchmakingConfiguration.ts
- sdk/nodejs/gamelift/matchmakingRuleSet.ts
- sdk/python/pulumi_aws/gamelift/matchmaking_configuration.py
- sdk/python/pulumi_aws/gamelift/matchmaking_rule_set.py
GameLift module has MatchmakingConfiguration and MatchmakingRuleSet resources that are implemented using patches and not maintained upstream. With this PR these resources are deprecated and are to be removed in the next major version. These resources have very modest usage numbers and have alternatives in the aws-native provider.
> Deprecate gamelift Matchmaking* resources

- provider/provider_yaml_test.go
- provider/test-programs/imds-auth/imds-v2/Pulumi.yaml
The `TestIMDSAuth` test frequently takes ~45 minutes to run. Looking into it more it looks like the `command:remote:CopyFile` takes the bulk of the time and I am not sure why. Copying the file to S3 via `BucketObjectV2` and then using the userData to copy the file from S3 during instance start up seems to be significantly faster
The test went from ~40minutes to ~4 minutes.
> chore: TestIMDSAuth is very slow

- provider/provider_yaml_test.go
Some of the YAML tests only need the AWS provider. Unless the SkipInstall option is specified, they will attempt to download the latest version of the provider before realizing there is an ambient in-process version to test with. This can cause sporadic CI failures unrelated to the test. Specifying SkipInstall optimizes away this redundant step.
Example failure log addressed here:
pulumiTest.go:103: failed to install packages and plugins: exit status 255
resource plugin aws installing
warning: Error downloading plugin: unknown version for plugin aws
Will retry in 80ms [1/5]
warning: Error downloading plugin: unknown version for plugin aws
Will retry in 160ms [2/5]
> chore: SkipInstall for tests that do not need it

- examples/go.mod
- examples/go.sum
- provider/go.mod
- provider/go.sum
Fixes #4342 
The fix is inherited through the https://github.com/pulumi/pulumi-terraform-bridge/commit/e4682154f1735880a1376774ccb593b4523410fe commit
This change bypasses our normal process of waiting for the next pulumi-terraform-bridge release to accelerate landing the fix. The changes between 3.89.0 and e4682154f1735880a1376774ccb593b4523410fe appear to be low-risk:
- https://github.com/pulumi/pulumi-terraform-bridge/pull/2306
- https://github.com/pulumi/pulumi-terraform-bridge/pull/2292
> Fix type-checking booleans

- examples/examples_nodejs_test.go
- examples/serverless-app-repository-application/Pulumi.yaml
- examples/serverless-app-repository-application/README.md
- examples/serverless-app-repository-application/index.ts
- examples/serverless-app-repository-application/package.json
- examples/serverless-app-repository-application/tsconfig.json
This deploys the [AthenaCloudwatchConnector](https://serverlessrepo.aws.amazon.com/applications/ap-south-1/313922868085/AthenaCloudwatchConnector) from the Serverless Application Repository
and sets it up as a data source in Athena. This allows users to query CloudWatch Logs using Athena.
Relates to #4393
> Add example for deploying an application from the serverless app repository

- examples/go.mod
- examples/go.sum
- provider/go.mod
- provider/go.sum
- provider/provider_nodejs_test.go
- provider/test-programs/regress-4446/Pulumi.yaml
- provider/test-programs/regress-4446/index.ts
- provider/test-programs/regress-4446/package.json
- provider/test-programs/regress-4446/tsconfig.json
Upgrading the bridge to https://github.com/pulumi/pulumi-terraform-bridge/commit/7864bb06caa76ac4adc8a7f44f8c8762f9a428cc in order to pull in the fix for https://github.com/pulumi/pulumi-aws/issues/4446.
This pulls in the following additional changes: https://github.com/pulumi/pulumi-terraform-bridge/compare/v3.90.0...7864bb06caa76ac4adc8a7f44f8c8762f9a428cc.
It's 3 low risk changes in total. Two are dynamic provider related changes and one test change(skipping a flaky test).
Fixes #4446
> Upgrade bridge to `7864bb0`

- patches/0064-Adapt-gamelift-matchmaking-resources.patch
Upstream [recently made a change](https://github.com/hashicorp/terraform-provider-aws/pull/39324)
so that a service cannot have resources across both sdkv1 and sdkv2.
This PR updates the `aws_gamelift_matchmaking_configuration` &
`aws_gamelift_matchmaking_rule_set` resources to sdkv2.
```console
$ make testacc TESTS=TestAccMatchmakingConfiguration PKG=gamelift
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.6 test ./internal/service/gamelift/... -v -count 1 -parallel 20 -run='TestAccMatchmakingConfiguration'  -timeout 360m
=== RUN   TestAccMatchmakingConfiguration_basic
=== PAUSE TestAccMatchmakingConfiguration_basic
=== RUN   TestAccMatchmakingConfiguration_tags
=== PAUSE TestAccMatchmakingConfiguration_tags
=== RUN …
```
> Update gamelift patches to sdkv2

- .github/workflows/master.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
We were a little out of date wrt ci-mgmt and this helps catch up on the Go versions, simply running `make ci-mgmt`
Fixes: https://github.com/pulumi/pulumi-aws/issues/4529
> make ci-mgmt

- provider/resources.go
- sdk/dotnet/Pulumi.Aws.csproj
- sdk/nodejs/package.json
This change removes the explicitly specified dependency on the core SDK from the schema so that the SDK generator can emit the minimum required version that's actually required for the generated provider SDK.
> Remove explicit dependency on core SDK

- provider/resources.go
- sdk/dotnet/Pulumi.Aws.csproj
Revert the change in a795267639fb926c36d459726e7ded11527fe812 for .NET as the default range emitted by sdkgen has a problem where NuGet will pick the minimum valid version that satisfies the range, rather than the latest possible version.
We can revert this after https://github.com/pulumi/pulumi/issues/17449 has been addressed.
> Set explicit version for .NET core SDK requirement

- provider/test-programs/gamelift-typescript/index.ts
Previously the gamelift test was using hardcoded names for the resources. This means only one test run can be executed at a time in CI. Otherwise one will fail with resource exists exceptions.
This fixes that by letting pulumi generate the names of the resources.
Fixes issues like https://github.com/pulumi/pulumi-aws/issues/4593
> Allow running gamelift test in parallel

- .github/workflows/aws-minimal-schema.yml
- provider/cmd/pulumi-resource-aws/generate.go
- provider/cmd/pulumi-resource-aws/main.go
The machinery for computing the AWS minimal schema is not working quite right. Looking at correcting the issues.
> Fix minimal schema computation

- provider/test-programs/imds-auth/imds-v2/Pulumi.yaml
The IMDSv2 test provisions a RC of the pulumi-aws-provider inside an AWS test account and checks if it can authenticate. Unfortunately something changed in the cloud that no longer permits unix programs to make changes to `/tmp`. The test relied to this for no good reason; the updated version creates a dedicated folder /home/ec2-user/repro to perform the check.
Fixes https://github.com/pulumi/pulumi-aws/issues/4670
> Fix IMDSv2 test to allow /tmp to be immutable

- .ci-mgmt.yaml
- .github/workflows/master.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
Slack notifications have been removed from ci-mgmt, but we still had
some specified in `.ci-mgmt.yaml`.
It looks like the Slack Secret was recently removed causing these jobs
to fail
closes #4691
> Remove slack notification from workflows

- provider/provider_nodejs_test.go
The flaky Lambda test might be caused by errors when flushing & closing the writers for the Lambda archives (e.g. out of space).
This change adds handling for those errors, to help understand why the files appear to not be found when executing the pulumi programs.
Relates to https://github.com/pulumi/pulumi-aws/issues/4731
> Handle writer errors when creating archives for Lambda test

- provider/test-programs/imds-auth/imds-v2/Pulumi.yaml
The ami filter we were using picked up a new AMI which had a minimum
volume size of 30. This PR modifies the filter to be a little more
specific to filter out these special case AMIs.
e.g.
- `amazon/al2023-ami-2023.6.20241111.0-kernel-6.1-x86_64` (good)
- `amazon/al2023-ami-ecs-neuron-hvm-2023.0.20241115-kernel-6.1-x86_64` (bad)
> Fix TestIMDS flaky test

- provider/provider_nodejs_test.go
Skipping `TestParallelLambdaCreation` because it started to be flaky.
Skipping the test for now to bring stability back into the release process while we investigate the issue.
Relates to #4731
> Skip flaky TestParallelLambdaCreation test

- .gitignore
- .mk/minimal_schema.mk
- provider/cmd/pulumi-resource-aws/main.go
In https://github.com/pulumi/pulumi-aws/commit/ea37daecbb549cbf52749147da1e1cb59c2d3cbe an error was introduced invalidating the production provider build - a subtle error by moving a `go:embed` directory to wildcards and FS type.
Per https://pkg.go.dev/embed#hdr-Strings_and_Bytes the path to a go:embed directory is a pattern. Apparently in the case of pulumi-aws CI the binary is built twice, once for testing and once for production release. In the for-testing build environment, schema-embed.json is a file which works as expected. In the for-production build environment, schema-embed.json is a folder created by the download-artifacts action that contains a single file. Before the change, this code worked correctly in both cases:
```
//go:embed schema-embed.json
var pulumiSchema []byte
``` …
> Remove embed wildcard

- provider/provider_yaml_test.go
- provider/resources.go
- provider/resources_test.go
- provider/test-programs/assume-role-session-tags/Pulumi.yaml
The provider wasn't sending the session tags when validating credentials. This caused perpetual credential check failures if users used the tags for enforcing access. This change fixes that.
Fixes #4849
> Pass Session Tags to credential validation check

- provider/doc_edits.go
- sdk/dotnet/Iam/PolicyAttachment.cs
- sdk/go/aws/iam/policyAttachment.go
- sdk/java/src/main/java/com/pulumi/aws/iam/PolicyAttachment.java
- sdk/nodejs/iam/policyAttachment.ts
- sdk/python/pulumi_aws/iam/policy_attachment.py
The `iam.PolicyAttachment` resource assumes exclusive management of IAM policies. Across the entire AWS account, all of the users/roles/groups to which a single policy is attached must be declared by a single `iam.PolicyAttachment` resource. This means that even any users/roles/groups that have the attached policy via any other mechanism (including other Pulumi resources) will have that attached policy revoked by this resource when it's deleted.
This is quite surprising to users, especially because there's no mention of it in the [Pulumi docs](https://www.pulumi.com/registry/packages/aws/api-docs/iam/policyattachment). 
The [warnings from the upstream provider](https://registry.terraform.io/providers/hashicorp/aws/5.78.0/docs/resources/iam_policy_attachment) were not carried into Pulumi …
> Replace Terraform with Pulumi to stop eliding iam.PolicyAttachment docs

- .ci-mgmt.yaml
- .github/workflows/master.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/run-acceptance-tests.yml
- patches/0025-move-shim-logic-to-upstream-as-a-patch.patch
- provider/shim_test.go
This removes the `go_test_shim` job defined in `extraTests` by making it a normal provider unit test instead of something that needs to be run as part of upstream.
We currently attempt to upload coverage as part of this test, but it [doesn't work](https://app.codecov.io/gh/pulumi/pulumi-aws). https://github.com/pulumi/ci-mgmt/pull/1224 will start uploading unit test coverage by default.
> Test shim as a normal unit test

- .github/workflows/aws-upstream-tests.yml
These tests are hitting quota limitations such as:
=== NAME  TestAccWAFRuleGroup_changeNameForceNew
rule_group_test.go:75: Step 1/3 error: Error running apply: exit status 1
Error: creating WAF Rule Group (tfaccyzotq): operation error WAF: CreateRuleGroup, https response error StatusCode: 400, RequestID: fcb7db05-54ed-4ab1-8a3b-cecdb02574fb, WAFLimitsExceededException: Operation would result in exceeding resource limits.
with aws_waf_rule_group.test,
on terraform_plugin_test.tf line 17, in resource "aws_waf_rule_group" "test":
17: resource "aws_waf_rule_group" "test" {
The intent of these tests was to smoke-test the upstream provider post-patching. However it appears that instead of smoke-testing the `wafv2` module that was patched the older `waf` module is being smoke-tested which might …
> chore: disable running `waf` upstream tests

- provider/resources.go
- sdk/nodejs/package.json
It looks like the `resolve` and `builtin-modules` dependencies aren't actually used anywhere, so stop depending on them.
The motivation for this change is that the dependency on `resolve` causes errors to be logged in logs during plugin discovery, because the package includes tests that have malformed `package.json` files. If we don't actually need the dependency it'd be nice to remove it so those errors are no longer logged (so users don't [ask us about them](https://github.com/pulumi/pulumi/issues/17578)).
Also remove the `builtin-modules` dependency while cleaning this up, since it doesn't appear to be used either AFAICT.
Similar to https://github.com/pulumi/pulumi-aws/pull/3238
Reference: https://github.com/pulumi/pulumi/issues/17578
> Remove unused npm dependencies

- renovate.json5
Adds a config file for the Renovate bot.
> chore: configure Renovate to ignore bridge and pkg/sdk dependencies

- .mk/minimal_schema.mk
- examples/minimal_schema_test.go
Since v6.62.1 minimal schema was not working. This is now fixed.
A change in standard CI scripts aimed at speeding up makefiles broke the assumptions of pulumi-aws specific Makefile extensions in .mk/minimal_schema.mk - that is CI would now run `make --touch provider schema` which would create an empty provider/cmd/pulumi-resource-aws/schema-minimal-embed.json file instead of recalculating it.
The change in question is: https://github.com/pulumi/ci-mgmt/pull/1157
The fix makes `minimal_schema` a PHONY target that may be a bit less efficient for rebuilding but is no longer affected by `make --touch`.
A regression test is added to catch this problem should it reoccur.
Fixes https://github.com/pulumi/pulumi-aws/issues/5016
> fix: Restore minimal schema

- examples/test-programs/assume-role-session-tags/Pulumi.yaml
The `TestAssumeRoleSessionTags` test frequently flakes due to the role
not being able to be assumed. This PR tries to fix that by switching the
role to use a CCAPI IAM Role which should perform more verification that
the role is ready.
re #4989, re #5035
> chore: switch assume-role-session-tags test to ccapi role

- .ci-mgmt.yaml
- .github/workflows/verify-release.yml
Reverts pulumi/pulumi-aws#5034
This did not quite work yet per:
https://github.com/pulumi/pulumi-aws/issues/5044
> Revert "chore: enable release verifcation"

- .ci-mgmt.yaml
- .github/workflows/prerequisites.yml
- .github/workflows/publish.yml
- .github/workflows/verify-release.yml
- Makefile
- examples/release-verification/Pulumi.yaml
- examples/release-verification/README.md
- examples/release-verification/index.ts
- examples/release-verification/package.json
- examples/release-verification/tsconfig.json
- examples/webserver-py/Pulumi.yaml
- upstream.sh
This enables release verification for AWS.
Tested by manually executing the `Verify-Release` workflow using this branch. Run can be seen here https://github.com/pulumi/pulumi-aws/actions/runs/12691069824
closes https://github.com/pulumi/ci-mgmt/issues/1265
> chore: enable release verification take 2

- docs/_index.md
This is probably one of our more visible examples so it should point to our recommended resource
> Update example in _index.md to use Bucket V2

- examples/examples_py_test.go
`TestRegress2534` started failing in CI, but still passes locally (see https://github.com/pulumi/pulumi-aws/issues/5100). There might be some side effects in CI that affect this.
Skipping the test for now to unblock the pipeline while I investigate the issue (see #5106).
Relates to #5106
Fixes #5100
> Skip `TestRegress2534`

- examples/examples_nodejs_test.go
- examples/regress-2868/package.json
Issue #3303 looks to be fixed so removing the `SkipRefresh` on the test.
> chore: enable refresh for regress-2868

- examples/examples_nodejs_test.go
- examples/rds-getengineversion/index.ts
Looks like AWS got rid of `15.2` and it now starts at `15.3`. Updating
to the highest version number to give us more time.
fixes #5128
> chore: fix TestRdsGetEngineVersion

- .ci-mgmt.yaml
- .github/actions/setup-tools/action.yml
- devbox.json
- examples/sqs-fifo-queue/csharp/testing-aws-fifo-dotnet.csproj
- examples/webserver-cs/AWS.Webserver.csproj
This repository does not need to pin .NET 6 version with respect to ci-mgmt defaults.
> chore: unpin .NET 6

- .ci-mgmt.yaml
- .github/actions/setup-tools/action.yml
- .github/workflows/build_sdk.yml
- .github/workflows/lint.yml
- .github/workflows/prerequisites.yml
- .github/workflows/test.yml
- .github/workflows/verify-release.yml
- examples/examples_nodejs_test.go
- provider/resources.go
This switches the AWS Access from hardcoded access keys that are pulled
from GitHub secrets to use Pulumi ESC environments.
re #3731
> Switch AWS access to use ESC

- .github/workflows/aws-upstream-tests.yml
- examples/examples_nodejs_test.go
- examples/test-programs/regress-5219/Pulumi.yaml
- examples/test-programs/regress-5219/index.ts
- examples/test-programs/regress-5219/package.json
- examples/test-programs/regress-5219/tsconfig.json
- patches/0091-Do-not-retry-route53resolver-LimitExceededException.patch
Fixes #5219 
LimitExceededException is no longer retried but fails fast.
Added a patch tracking issue:
https://github.com/pulumi/pulumi-aws/issues/5385
Sent an upstream PR.
> Fix route53.ResolverEndpoint hangs with 6-10 IPs

- examples/examples_yaml_test.go
- examples/go.mod
- examples/go.sum
- examples/test-programs/security-group/Pulumi.yaml
- examples/test-programs/security-group/security-group-1/Pulumi.yaml
- provider/resources.go
- sdk/dotnet/Ec2/Inputs/SecurityGroupEgressArgs.cs
- sdk/dotnet/Ec2/Inputs/SecurityGroupEgressGetArgs.cs
- sdk/dotnet/Ec2/Inputs/SecurityGroupIngressArgs.cs
- sdk/dotnet/Ec2/Inputs/SecurityGroupIngressGetArgs.cs
- sdk/go/aws/ec2/pulumiTypes.go
- sdk/java/src/main/java/com/pulumi/aws/ec2/inputs/SecurityGroupEgressArgs.java
- sdk/java/src/main/java/com/pulumi/aws/ec2/inputs/SecurityGroupIngressArgs.java
- sdk/python/pulumi_aws/ec2/_inputs.py
- sdk/python/pulumi_aws/ec2/outputs.py
This PR adds Default values for the `description` fields on the `ingress` and `egress` properties of `aws_security_group`. This default was previously implicitly applied by the AWS API but only after creation resulting in a mismatch between the plan value and the resulting state. This inconsistency prevents the custom `SetHash` function of `aws_security_group` to correctly apply to the planned value, resulting in a warning during preview.
Applying the default in the schema fixes the issue and correctly displays an improved preview for the resource:
```
~ ingress: [
+ [0]: {
+ cidrBlocks : [
+     [0]: "0.0.0.0/0"
]
+ description: ""
+ fromPort   : 80
+ protocol   : "tcp"
+ self       : false
+ toPort     : 80
}
]
```
instead of
```
~ ingress: [
~ [0]: {
+ __defaults    : [
+     [0]: …
```
> Make implicit defaults explicit for aws_security_group ingress and egress description fields

- examples/bucket-to-bucketv2/Pulumi.yaml
- examples/bucket-to-bucketv2/step1/Pulumi.yaml
- examples/examples_yaml_test.go
This adds a test that shows that changing the type of a bucket from `Bucket` to `BucketV2` works without a diff.
closes #4471
> Add test for Bucket to BucketV2 alias

- provider/resources.go
- sdk/dotnet/Ec2/Inputs/SecurityGroupEgressArgs.cs
- sdk/dotnet/Ec2/Inputs/SecurityGroupEgressGetArgs.cs
- sdk/dotnet/Ec2/Inputs/SecurityGroupIngressArgs.cs
- sdk/dotnet/Ec2/Inputs/SecurityGroupIngressGetArgs.cs
- sdk/go/aws/ec2/pulumiTypes.go
- sdk/java/src/main/java/com/pulumi/aws/ec2/inputs/SecurityGroupEgressArgs.java
- sdk/java/src/main/java/com/pulumi/aws/ec2/inputs/SecurityGroupIngressArgs.java
- sdk/python/pulumi_aws/ec2/_inputs.py
- sdk/python/pulumi_aws/ec2/outputs.py
Reverts #5442 
The root cause of https://github.com/pulumi/pulumi-aws/issues/5438 is now fixed in the bridge https://github.com/pulumi/pulumi-terraform-bridge/releases/tag/v3.107.0 and we no longer need the workaround.
This also will alleviate https://github.com/pulumi/pulumi-aws/issues/5483
We need to remember to update pulumi-eks with the version that ships this change to avoid tripping up this error again:
https://github.com/pulumi/pulumi-eks/issues/1752
> Revert #5442

- provider/pkg/minimalschema/minimalschema_test.go
In preparation for the upcoming bridge update, `"#/resources/pulumi:providers:aws` needs to be tolerated although it appears to be a dangling reference.
> chore: tolerate provider self-references

- docs/v7-upgrade.md
This starts the docs to keep track of breaking changes that are being
made to v7
> [7.0.0-alpha]: Add v7 upgrade docs

- .github/workflows/prerequisites.yml
- .github/workflows/run-acceptance-tests.yml
This should run schema check against the `7.0.0-alpha` branch for pull requests made against it. 
I don't think that we need to worry about central CI management clobbering this either.
> Compare schema from v7 branch

- docs/v7-upgrade.md
- examples/examples_nodejs_test.go
- examples/migrate-resource-refs/elasticbeanstalk/v7/index.ts
- provider/resources.go
- sdk/nodejs/elasticbeanstalk/environment.ts
This pull request resolves the final dangling reference to what is a resource type.
Instead of `version: appVersion`, users will now need to use `version: appVersion.name`. This is documented, and the case is added to the test.
edit: also a test for lambdaFunction is enabled that was missed previously.
Closes https://github.com/pulumi/pulumi-aws/issues/5540.
> Migrate applicationversion to applicationversion.name in v7

- examples/bucket-sidecar-renames/Pulumi.yaml
- examples/bucket-sidecar-renames/step1/Pulumi.yaml
- examples/bucket-to-bucket/Pulumi.yaml
- examples/bucket-to-bucket/step1/Pulumi.yaml
- examples/bucketv2-to-bucket/Pulumi.yaml
- examples/bucketv2-to-bucket/step1/Pulumi.yaml
- examples/examples_yaml_test.go
- examples/iam-policy-document/csharp/AWS.Webserver.csproj
- examples/provider_test.go
This enables a couple of tests to test the upgrade of the
Bucket/BucketV2 related resources. When the upgrade is performed with
`--refresh --run-program` it produces no diff.
closes #5514
> Enable bucket upgrade tests

- examples/examples_nodejs_test.go
Skipping these for now since we have backtracked on the decision to
remove these resource references.
re #5540
> [v7]: Skip resource reference migration tests

- examples/iam-policy-document/ts/index.ts
- provider/resources.go
- sdk/nodejs/ecr/index.ts
- sdk/nodejs/ecr/lifecyclePolicyDocument.ts
- sdk/nodejs/iam/documents.ts
- sdk/nodejs/tsconfig.json
Re-exporting the `PolicyDocument` and `PolicyStatement` types. This
avoids an unnecessary breaking change for users.
> [v7]: Re-export iam PolicyDocument types

- sdk/nodejs/ecr/lifecyclePolicyDocument.ts
Added tagPatternLists parameter in getLifecyclePolicyDocument function.
Fixes: #5119
> Added tagPatternLists type to getLifecyclePolicyDocument in ecr

- docs/version-7-upgrade.md
- provider/resources.go
- sdk/dotnet/Eks/Cluster.cs
- sdk/go/aws/eks/cluster.go
- sdk/go/aws/eks/pulumiTypes.go
- sdk/java/src/main/java/com/pulumi/aws/eks/Cluster.java
- sdk/java/src/main/java/com/pulumi/aws/eks/inputs/ClusterState.java
- sdk/nodejs/eks/cluster.ts
- sdk/python/pulumi_aws/eks/cluster.py
Follow up to #5655. The upstream API only returns a single item so we
should remove the list version not the single item version
> [v7]: cluster certificateAuthority only returns a single item

- docs/version-7-upgrade.md
This todo is no longer needed. I've tested this out and there is nothing
users need to do except remove the field.
> [v7]: remove old todo

- examples/iam-policy-document/doc-go/go.mod
- examples/tags-combinations-go/go.mod
- examples/webserver-go/go.mod
Using go mod replace causes the verify-release job to fail. This pull request removes the replace, and pins the test version to SDK v7.
> Do not replace Go examples with local SDK

- examples/examples_go_test.go
This pull request removes a single test that was added for verification and should have remained local. It's part of the Tags test suite already.
> Remove extraneous test

- examples/examples_nodejs_test.go
- examples/test-programs/global-region-res/Pulumi.yaml
- examples/test-programs/global-region-res/README.md
- examples/test-programs/global-region-res/index.ts
- examples/test-programs/global-region-res/package.json
- examples/test-programs/global-region-res/tsconfig.json
- provider/region.go
Global resources that had a `region` argument in v6 have deprecated the
`region` argument and added a new resource specific region argument
(e.g. `StackSetInstance` has a `stackSetInstanceRegion` argument).
This PR adds an additional check to exclude any `region` argument that
has been deprecated.
fixes #5707
> Fix region injection for global resources

- examples/eks-remove-addons/Pulumi.yaml
- examples/eks-remove-addons/README.md
- examples/eks-remove-addons/index.ts
- examples/eks-remove-addons/package.json
- examples/eks-remove-addons/tsconfig.json
- examples/examples_nodejs_test.go
- patches/0026-aws_eks_cluster-implement-default_addons_to_remove.patch
- provider/resources.go
- sdk/dotnet/Eks/Cluster.cs
- sdk/go/aws/eks/cluster.go
- sdk/java/src/main/java/com/pulumi/aws/eks/Cluster.java
- sdk/java/src/main/java/com/pulumi/aws/eks/ClusterArgs.java
- sdk/java/src/main/java/com/pulumi/aws/eks/inputs/ClusterState.java
- sdk/nodejs/eks/cluster.ts
- sdk/python/pulumi_aws/eks/cluster.py
Adding back the patch for `defaultAddonsToRemove` by popular demand.
fixes https://github.com/pulumi/pulumi-aws/issues/5715
re https://github.com/pulumi/pulumi-aws/issues/4755
> Add back eks defaultAddonsToRemove property

- examples/eks-remove-addons/index.ts
- provider/resources.go
- sdk/dotnet/Eks/Cluster.cs
- sdk/go/aws/eks/cluster.go
- sdk/java/src/main/java/com/pulumi/aws/eks/Cluster.java
- sdk/java/src/main/java/com/pulumi/aws/eks/ClusterArgs.java
- sdk/java/src/main/java/com/pulumi/aws/eks/inputs/ClusterState.java
- sdk/nodejs/eks/cluster.ts
- sdk/python/pulumi_aws/eks/cluster.py
In v6 the property had an `s` at the end. The previous PR incorrectly removed the `s`.
https://github.com/pulumi/pulumi-aws/blob/v6.83.0/sdk/nodejs/eks/cluster.ts#L644
> Fix `defaultAddonsToRemove` should be `defaultAddonsToRemoves`
