CONTRIBUTING.md

Hopefully this should prevent @joeduffy from having to answer the same questions repeatedly!

Add notes about generated code to CONTRIBUTING.md

---

resources.go
sdk/go/aws/elasticache/cluster.go
sdk/nodejs/elasticache/cluster.ts
sdk/python/pulumi_aws/elasticache/cluster.py

Auto-name aws.elasticache.Cluster#clusterId

---

examples/minimal/package.json
examples/multiple-regions/package.json
examples/serverless-raw/package.json
examples/webserver-comp/package.json
examples/webserver/package.json
examples/webserver/variants/get/package.json
examples/webserver/variants/ssh/package.json
examples/webserver/variants/ssh_description/package.json
examples/webserver/variants/zones/package.json
sdk/nodejs/package.json
tests/delete_before_create/mount_target/step1/package.json
tests/serverless_functions/package.json

Toward fixing: https://github.com/pulumi/pulumi/issues/1668

Use the latest version of TS.

---

overlays/nodejs/cloudwatch/logGroupMixins.ts
overlays/nodejs/lambda/lambdaMixins.ts
overlays/nodejs/serverless/function.ts
overlays/nodejs/sqs/sqsMixins.ts
sdk/nodejs/cloudwatch/logGroupMixins.ts
sdk/nodejs/lambda/lambdaMixins.ts
sdk/nodejs/serverless/function.ts
sdk/nodejs/sqs/sqsMixins.ts

https://github.com/pulumi/pulumi-aws/pull/331/files?w=1
will make the diff easier to read.

Renames based on PR feedback.

---

resources.go

Fix a few omissions from #330.

---

sdk/nodejs/apigateway/experimental/api.ts

We really need to do this all the time with all our APIs.  Things work fine if you're using TS.  But if you use JS, you don't know it won't work and you'll often get a cryptic crash.

Add input validation to routes.

---

sdk/nodejs/lambda/lambdaMixins.ts

fixes https://github.com/pulumi/pulumi-aws/issues/348

Do not make callback args mandatory as AWS does not require them.

---

sdk/nodejs/ec2/instanceType.ts

Fixes #357 for now, in lieu of autogenerating this list.

Add M5 and M5d instance type constants

---

Gopkg.lock

Pull in latest tfbridge changes

---

sdk/nodejs/ec2/instanceType.ts

Not sure if this file is manually maintained or auto-generated

add p3 instance to instanceType

---

sdk/nodejs/apigateway/experimental/api.ts

This ends up just producing garbage in the checkpoint like:

Don't put real objects in the value we convert into the swagger string.

---

sdk/nodejs/ec2/instanceType.ts

adds all the newer instance types: A1, C5, G3, M5a, R5, X1e, Z1d, and few random others

add more instance types

---

CHANGELOG.md

I'll cut the release after this is merged.

Update CHANGELOG.md for 0.16.6

---

CHANGELOG.md
resources.go
sdk/nodejs/iam/instanceProfile.ts
sdk/nodejs/iam/rolePolicyAttachment.ts

Fix typing of Role properties

---

.golangci.yml

Tracking issue: https://github.com/pulumi/pulumi/issues/2629

Disable specific linter due to OOM issues

---

CHANGELOG.md
examples/examples_test.go
examples/ignoreChanges/.gitignore
examples/ignoreChanges/Pulumi.yaml
examples/ignoreChanges/index.ts
examples/ignoreChanges/package.json
examples/ignoreChanges/step1/index.ts
examples/ignoreChanges/tsconfig.json
resources.go
sdk/nodejs/package.json
sdk/python/setup.py

Pulls in the `ignoreChanges` and adds a test case.

Bump pulumi/pulumi to 0.17.8

---

examples/examples_test.go
go.mod
go.sum
sdk/go/aws/config/config.go
sdk/nodejs/config/vars.ts
sdk/nodejs/utilities.ts
sdk/python/pulumi_aws/config/vars.py
sdk/python/pulumi_aws/utilities.py
sdk/python/setup.py

This should fix the python issues we are seeing.  As part of this work, I am going to start running our one Python test as part of PRs, to have some python coverage.

Pull in newer pulumi-terraform

---

CHANGELOG.md
examples/examples_test.go
examples/ssmparameter/Pulumi.yaml
examples/ssmparameter/README.md
examples/ssmparameter/index.ts
examples/ssmparameter/package.json
examples/ssmparameter/tsconfig.json
resources.go
sdk/nodejs/ssm/index.ts
sdk/nodejs/ssm/parameter.ts
sdk/nodejs/ssm/parameterType.ts
sdk/nodejs/tsconfig.json

Addition of Enums for SSM Parameter Types

---

CHANGELOG.md
resources.go
sdk/nodejs/rds/cluster.ts
sdk/nodejs/rds/clusterInstance.ts
sdk/nodejs/rds/engineMode.ts
sdk/nodejs/rds/engineType.ts
sdk/nodejs/rds/index.ts
sdk/nodejs/tsconfig.json

Adding constants for RDS Cluster EngineType and EngineMode

---

CHANGELOG.md
examples/webserver/index.ts
resources.go
sdk/nodejs/ec2/index.ts
sdk/nodejs/ec2/protocolType.ts
sdk/nodejs/tsconfig.json

Adding constants for EC2 Security Group Protocols

---

CHANGELOG.md
examples/examples_test.go
examples/route53/Pulumi.yaml
examples/route53/README.md
examples/route53/index.ts
examples/route53/package.json
examples/route53/tsconfig.json
resources.go
sdk/nodejs/route53/index.ts
sdk/nodejs/route53/record.ts
sdk/nodejs/route53/recordType.ts
sdk/nodejs/tsconfig.json

Adding Route53 RecordType constants

---

CHANGELOG.md
resources.go
sdk/nodejs/iam/policy.ts

Adding the ability to specify PolicyDocument in aws.iam.Policy

---

CHANGELOG.md
resources.go
sdk/nodejs/s3/bucket.ts

Add the ability to pass a PolicyDocument to aws.s3.Bucket policy field

---

sdk/nodejs/lambda/lambdaMixins.ts

Will be helpful in the awsx repo for some of the work i'm doing.

Add helper function for typechecking.

---

CHANGELOG.md
sdk/nodejs/lambda/runtimes.ts

Update the available Lambda Runtimes

---

CHANGELOG.md
resources.go
sdk/nodejs/codebuild/webhook.ts
sdk/nodejs/rds/clusterInstance.ts
sdk/nodejs/rds/index.ts
sdk/nodejs/rds/instance.ts
sdk/nodejs/rds/instanceType.ts
sdk/nodejs/tsconfig.json

Adding constants for RDS InstanceTypes

---

sdk/nodejs/cloudwatch/eventRuleMixins.ts
sdk/nodejs/cloudwatch/logGroupMixins.ts
sdk/nodejs/dynamodb/dynamodbMixins.ts
sdk/nodejs/kinesis/kinesisMixins.ts
sdk/nodejs/s3/s3Mixins.ts
sdk/nodejs/sns/snsMixins.ts
sdk/nodejs/sqs/sqsMixins.ts

Fixes issue i introduced in https://github.com/pulumi/pulumi-aws/pull/623

Properly parent resources

---

CHANGELOG.md
examples/examples_test.go
examples/lambda-layer/.gitignore
examples/lambda-layer/Pulumi.yaml
examples/lambda-layer/index.ts
examples/lambda-layer/package.json
examples/lambda-layer/tsconfig.json
resources.go
sdk/go/aws/lambda/layerVersion.go
sdk/nodejs/lambda/layerVersion.ts
sdk/python/pulumi_aws/lambda_/layer_version.py

Fixes: #591
@lukehoban we should have a chat about this before we merge it - I am not quite sure that this has no unintended side-effects

Adding the ability to pass code directly to lambda layer_version

---

CHANGELOG.md
resources.go
sdk/nodejs/rds/index.ts
sdk/nodejs/rds/instance.ts
sdk/nodejs/rds/storageType.ts
sdk/nodejs/tsconfig.json

this is a reminder for me to add constants for RDS StorageType

Adding module containing constants for RDS DB Instance StorageType

---

sdk/nodejs/dynamodb/dynamodbMixins.ts

Fixes https://github.com/pulumi/pulumi-aws/issues/646
This improves the user experience here.  Instead of a useless error message like:
```
error: Plan apply failed: Error creating Lambda event source mapping: ValidationException: 1 validation error detected: Value '' at 'eventSourceArn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*)
status code: 400, request id: 429cd339-bef2-4ffc-9745-43388b7e8ab6
```
You now get:
```
aws:dynamodb:TableEventSubscription (notify):
error: Error: Table must be created with `streamEnabled: true` to support listening for events.
```

Produce better error if a table doesn't support onEvent callback.

---

CHANGELOG.md
examples/ecr/Pulumi.yaml
examples/ecr/README.md
examples/ecr/index.ts
examples/ecr/package.json
examples/ecr/tsconfig.json
examples/examples_test.go
resources.go
sdk/nodejs/ecr/index.ts
sdk/nodejs/ecr/lifecyclePolicy.ts
sdk/nodejs/ecr/lifecyclePolicyDocument.ts
sdk/nodejs/iam/documents.ts
sdk/nodejs/tsconfig.json

Adding an ECR Lifecycle Document Type

---

examples/multiple-regions/index.ts

Use sync method

---

CHANGELOG.md
sdk/nodejs/ec2/instanceType.ts

Add support for T3a instance types

---

CHANGELOG.md
sdk/nodejs/iam/documents.ts

Allow IAM document Conditions to be arrays

---

Makefile

Use the build-package-docs script.

Build new docs in CI on new releases.

---

sdk/nodejs/README.md

Fix links and ensure they have a trailing slash.

Avoid 302 redirects

---

CHANGELOG.md
resources.go
sdk/go/aws/appsync/apiKey.go
sdk/go/aws/docdb/subnetGroup.go
sdk/go/aws/mediapackage/channel.go
sdk/go/aws/neptune/subnetGroup.go
sdk/go/aws/rds/subnetGroup.go
sdk/nodejs/appsync/apiKey.ts
sdk/nodejs/docdb/subnetGroup.ts
sdk/nodejs/mediapackage/channel.ts
sdk/nodejs/neptune/subnetGroup.ts
sdk/nodejs/rds/subnetGroup.ts
sdk/python/pulumi_aws/appsync/api_key.py
sdk/python/pulumi_aws/docdb/subnet_group.py
sdk/python/pulumi_aws/mediapackage/channel.py
sdk/python/pulumi_aws/neptune/subnet_group.py
sdk/python/pulumi_aws/rds/subnet_group.py

Overriding default of Managed by Terraform entries

---

go.mod
go.sum
sdk/dotnet/Pulumi.Aws.csproj

We will use this from pulumi language plugin to determine the set of required resource-plugins that need to be installed before running a dotnet app.

Directly embed version file as a content file in our reosurce packages.

---

CHANGELOG.md
Makefile

And fix .NET version generation.

Update the CHANGELOG for v1.8.0

---

CHANGELOG.md
resources.go
sdk/nodejs/appsync/function.ts
sdk/nodejs/glue/catalogDatabase.ts
sdk/nodejs/glue/catalogTable.ts

Add custom name transformations for appsync_func and glue_

---

CHANGELOG.md
resources.go
sdk/nodejs/iam/groupPolicyAttachment.ts
sdk/nodejs/iam/policyAttachment.ts
sdk/nodejs/iam/userPolicyAttachment.ts

Allow use of string or Type in IAM PolicyAttachment resources

---

resources.go

This has been moved to pulumi-terraform-bridge
Related: pulumi/home#607

Remove the custom renaming logic for resources and datasources

---

CHANGELOG.md
examples/lambda-layer/index.ts
examples/serverless-raw/index.ts
sdk/nodejs/lambda/lambdaMixins.ts

Fixes: #774
This is in preparation for AWS EOLing NodeJS 8.x
@lukehoban I would appreciate your thoughts on this please

Default Lambda NodeJS runtime to 10.x

---

CHANGELOG.md
resources.go
sdk/dotnet/Eks/NodeGroup.cs
sdk/go/aws/eks/nodeGroup.go
sdk/nodejs/eks/nodeGroup.ts
sdk/python/pulumi_aws/eks/node_group.py

Part of pulumi/pulumi-eks#294.

Autoname aws.eks.NodeGroup nodeGroupName

---

sdk/nodejs/lambda/lambdaMixins.ts

Fix link in doc comment

---

examples/alb-legacy/index.ts
examples/alb-new/index.ts
examples/alb-new/step2/index.ts
examples/webserver/variants/zones/index.ts

Use async data sources.

---

resources.go
sdk/dotnet/Pulumi.Aws.csproj

I need to update the templates and for that I need the latest Pulumi 1.11.0 with some new API

Update to Pulumi 1.11.0

---

sdk/nodejs/lambda/lambdaMixins.ts

Fixes: https://github.com/pulumi/docs/issues/2589

Fixup docs for Lambda Mixins

---

CHANGELOG.md
resources.go
sdk/dotnet/Ec2/Instance.cs
sdk/nodejs/ec2/instance.ts

Add deprecation message to ec2.Instance securityGroups

---

Makefile
provider/cmd/pulumi-resource-aws/.gitignore

And do not check it in, as its version will change on each regeneration.

Properly regenerate the schema.

---

CHANGELOG.md
sdk/nodejs/lambda/runtimes.ts

Add support for Lambda DotNet 3.1 Runtime

---

sdk/nodejs/iam/documents.ts

Fixes: #923
This allows the docs to pick them up

Turning the iam.PolicyDocument comments into TypeScript comments

---

CHANGELOG.md
sdk/nodejs/dynamodb/dynamodbMixins.ts
sdk/nodejs/kinesis/kinesisMixins.ts

Update `dynamodb.TableEventSubscriptionArgs` with latest Event Source Mapping params

---

CHANGELOG.md
sdk/nodejs/iam/managedPolicies.ts

https://console.aws.amazon.com/iam/home#/policies/arn:aws:iam::aws:policy/AmazonRDSDataFullAccess$jsonEditor

Add support for missing TypeScript Iam policy (AmazonRDSDataFullAccess)

---

CHANGELOG.md
sdk/nodejs/iam/managedPolicies.ts

Add support for aws.iam.ManagedPolicies.AWSCodeDeployRoleForECS

---

CHANGELOG.md
sdk/nodejs/iam/managedPolicies.ts

Add support for aws.iam.ManagedPolicies.AWSXRayDaemonWriteAccess

---

CHANGELOG.md
provider/resources.go

Relax naming restrictions on   to allow 40 characters

---

CHANGELOG.md
provider/resources.go
sdk/dotnet/AppSync/DataSource.cs
sdk/dotnet/AppSync/Function.cs
sdk/dotnet/AppSync/Resolver.cs
sdk/go/aws/appsync/dataSource.go
sdk/go/aws/appsync/function.go
sdk/nodejs/appsync/dataSource.ts
sdk/nodejs/appsync/function.ts
sdk/nodejs/appsync/resolver.ts
sdk/python/pulumi_aws/appsync/data_source.py
sdk/python/pulumi_aws/appsync/function.py
sdk/python/pulumi_aws/appsync/resolver.py

Update naming convertions on appsync.DataSource

---

CHANGELOG.md
provider/resources.go
sdk/dotnet/DirectoryService/Directory.cs
sdk/dotnet/Workspaces/Directory.cs
sdk/go/aws/directoryservice/directory.go
sdk/go/aws/workspaces/directory.go
sdk/nodejs/directoryservice/directory.ts
sdk/nodejs/workspaces/directory.ts
sdk/python/pulumi_aws/directoryservice/directory.py
sdk/python/pulumi_aws/workspaces/directory.py

Disable Autonaming on directoryservice.Directory

---

CHANGELOG.md
provider/go.mod
provider/go.sum

Upgrade to v2.10.4 pulumi-terraform-bridge to fix a regression on pulumi config set

---

provider/go.mod
provider/go.sum
sdk/dotnet/Batch/ComputeEnvironment.cs
sdk/go/aws/batch/computeEnvironment.go
sdk/nodejs/batch/computeEnvironment.ts
sdk/python/pulumi_aws/batch/compute_environment.py

Fixup the AWS Batch Compute Environment example

---

CHANGELOG.md
provider/go.mod
provider/go.sum

Fixes: https://github.com/pulumi/pulumi/issues/5633
Fixes: https://github.com/pulumi/pulumi-aws/issues/1185

Upgrade to pulumi-terraform-bridge v2.12.1

---

CHANGELOG.md
provider/go.mod
provider/go.sum
sdk/dotnet/Athena/Workgroup.cs
sdk/go/aws/athena/workgroup.go
sdk/nodejs/athena/workgroup.ts
sdk/python/pulumi_aws/athena/workgroup.py

Upgrade to v3.14.1 of the AWS Terraform Provider

---

CHANGELOG.md
provider/resources.go
sdk/dotnet/Msk/Cluster.cs
sdk/go/aws/msk/cluster.go
sdk/nodejs/msk/cluster.ts
sdk/python/pulumi_aws/msk/cluster.py

Enabling the autonaming of MSK Clusters

---

CHANGELOG.md
provider/go.mod
provider/go.sum
sdk/dotnet/Lambda/EventSourceMapping.cs
sdk/go/aws/lambda/eventSourceMapping.go
sdk/nodejs/lambda/eventSourceMapping.ts
sdk/python/pulumi_aws/lambda_/event_source_mapping.py

Add support for MSK Topics to Lambda Event Source Mapping

---

CHANGELOG.md
provider/resources.go

Ensure autonamed FIFO queues have .fifo suffix

---

provider/go.mod
provider/go.sum
sdk/dotnet/CloudTrail/Trail.cs
sdk/go/aws/cloudtrail/trail.go
sdk/nodejs/cloudtrail/trail.ts
sdk/python/pulumi_aws/cloudtrail/trail.py

Fix the aws.CloudTrail.Trail examples to include the required fields

---

provider/go.mod
provider/go.sum
sdk/dotnet/Acm/Certificate.cs
sdk/go/aws/acm/certificate.go
sdk/nodejs/acm/certificate.ts
sdk/python/pulumi_aws/acm/certificate.py

Fixes: https://github.com/pulumi/docs/issues/5084

Removing create_before_destroy from aws.acm.Certificate docs

---

CHANGELOG.md
README.md
sdk/python/README.md

Adding configuration details to README

---

CHANGELOG.md
sdk/nodejs/kinesis/kinesisMixins.ts
sdk/nodejs/lambda/lambdaMixins.ts
sdk/nodejs/sqs/sqsMixins.ts

Ensure sdk/nodejs lambda mixins have appropriate permissions

---

CHANGELOG.md
provider/go.mod
provider/go.sum

Ensure emr.Cluster is destroyed before destroying dependent resources

---

CHANGELOG.md
sdk/nodejs/ecs/container.ts

Part of https://github.com/pulumi/pulumi-awsx/issues/682

[NodeJS] Add environmentFile to container definition type

---

CHANGELOG.md
provider/go.mod
provider/go.sum

Remove unnecessary default in aws.lakeformation.Permissions CatalogResource

---

Makefile

Fixes: https://github.com/pulumi/pulumi/issues/8001﻿

Adding empty go.mod to exclude python, nodejs and dotnet from the go.modules

---

CHANGELOG.md
provider/resources.go

add autonaming support for mq.Broker

---

CHANGELOG.md
provider/go.mod
provider/go.sum
provider/shim/go.mod
provider/shim/go.sum
sdk/dotnet/Route53/ResolverDnsSecConfig.cs
sdk/dotnet/Route53/ResolverFirewallRuleGroup.cs
sdk/go/aws/route53/resolverDnsSecConfig.go
sdk/go/aws/route53/resolverFirewallRuleGroup.go
sdk/nodejs/route53/resolverDnsSecConfig.ts
sdk/nodejs/route53/resolverFirewallRuleGroup.ts
sdk/python/pulumi_aws/route53/resolver_dns_sec_config.py
sdk/python/pulumi_aws/route53/resolver_firewall_rule_group.py

Ensure aws.route53 classes don't have duplicate Id parameters

---

provider/go.mod
provider/go.sum
provider/shim/go.mod
provider/shim/go.sum
sdk/nodejs/backup/selection.ts
sdk/python/pulumi_aws/backup/selection.py

Upgrade terraform-provider-aws to v3.74.1

---

provider/go.mod
provider/go.sum
provider/shim/go.mod
provider/shim/go.sum

Upgrade terraform-provider-aws to v3.74.3

---

provider/resources.go
sdk/dotnet/Lambda/Enums.cs
sdk/go/aws/lambda/pulumiEnums.go
sdk/nodejs/types/enums/lambda/index.ts
sdk/python/pulumi_aws/lambda_/_enums.py

Allow dotnet 6 lambda runtime

---

provider/resources.go
sdk/dotnet/Ec2/Enums.cs
sdk/dotnet/Enums.cs
sdk/dotnet/Iam/Enums.cs
sdk/go/aws/ec2/pulumiEnums.go
sdk/go/aws/iam/pulumiEnums.go
sdk/go/aws/pulumiEnums.go
sdk/nodejs/types/enums/ec2/index.ts
sdk/nodejs/types/enums/iam/index.ts
sdk/nodejs/types/enums/index.ts
sdk/python/pulumi_aws/_enums.py
sdk/python/pulumi_aws/ec2/_enums.py
sdk/python/pulumi_aws/iam/_enums.py

* add support for aws SecretsManagerReadWrite - superceeds #1855 #1833
* Add support for g4ad.xlarge and g4ad.2xlarge EC2 instance types - superceeds #1729
* Add support for ap-northeast-3 region - superceeds #1595

community prs

---

provider/resources.go

Fixes #2075
Update: I built this locally and verified it behaves as expected. :tada:

ECRLifecyclePolicy: Ensure deleteBeforeReplace is true

---

provider/resources.go

validation: Ensure we can validate the user has a region set

---

provider/resources.go

Fixes https://github.com/pulumi/pulumi-aws/issues/2081.

apigatewayIntegration: Ensure deleteBeforeReplace is defaults to true

---

provider/resources.go

Fixes: #2108
Fixes: #2104
Fixes: #2105
The need for an explict check on the configuration parameter OR the
environment variable is not quite correct, the TF provider does
fall back to using the sharedCredentials as that also includes the
region.
This also ensures we check `sharedCredentialsFiles` and not just
`sharedCredentialsFile` configuration

provider: Remove explicit config and EnvVar Check for Region

---

README.md
sdk/python/README.md

This PR is just a fresh cherry-pick of #2152 by @ abhishekaj. Thank you!

Updating authentication doc to use BoolPtr in go

---

docs/resource/aws_acm_certificate_validation.examples.md
sdk/python/pulumi_aws/acm/certificate_validation.py

This PR is a cherry-pick of @jbertman's #2213 plus regenerating the SDKs.

ACM cert validation example fixes

---

sdk/nodejs/lambda/lambdaMixins.ts

Warn when a secret is captured by an `aws.lambda.CallbackFunction`

---

examples/callbackfunction/Pulumi.yaml
examples/callbackfunction/index.ts
examples/callbackfunction/package.json
examples/callbackfunction/tsconfig.json
examples/examples_nodejs_test.go
examples/go.mod
sdk/nodejs/lambda/lambdaMixins.ts

Also, improve test coverage of CallbackFunction.
Fixes #1649.

Accept Input<ARN> for role on CallbackFunction

---

.github/workflows/main.yml
.github/workflows/master.yml
.github/workflows/nightly-test.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/run-acceptance-tests.yml

Change default descriptions to "Managed by Pulumi"

---

provider/resources.go
sdk/dotnet/Enums.cs
sdk/go/aws/pulumiEnums.go
sdk/java/src/main/java/com/pulumi/aws/enums/Region.java
sdk/nodejs/types/enums/index.ts
sdk/python/pulumi_aws/_enums.py

[Requested on community Slack](https://pulumi-community.slack.com/archives/CRH5ENVDX/p1678226681555839)

Add new ap-southeast-4 region

---

sdk/nodejs/sns/snsMixins.ts

This should be enough to correctly expose the rest of the arguments of the topic subscription.

Mapped TopicSubscription args

---

Makefile

Same change as just got rolled out to ecosystem providers https://github.com/pulumi/ci-mgmt/pull/386 - applied manually to this provider.

Allow custom build parallelism

---

provider/go.mod
provider/go.sum
provider/resources.go

Add auto-mapping

---

upstream-patches/0001-Add-TagsSchemaTrulyComputed-definition.patch
upstream-patches/0002-Conns-user-agent.patch
upstream-patches/0003-Add-S3-legacy-bucket-to-resources.patch
upstream-patches/0004-Marks-SSE-Configuration-as-Computed-for-Legacy-S3-Bu.patch
upstream-patches/0005-De-deprecate-bucket_object.patch
upstream-patches/0006-Remove-lakeformation-catalog_resource-default.patch
upstream-patches/0007-Workaround-SSM-Parameter-tier-bug.patch
upstream-patches/0008-Add-EKS-cluster-default_addons_to_remove.patch
upstream-patches/0009-Add-EKS-cluster-certificate_authorities-plural.patch
upstream-patches/0010-Workaround-Autoscaling-launch_configuration-associat.patch
upstream-patches/0011-Add-ECR-credentials_data_source.patch
upstream-patches/0012-Revert-framework-conversions.patch
upstream-patches/0013-Add-custom-appautoscaling-examples.patch
upstream-patches/0014-Add-dedicated_host-docs.patch
upstream-patches/0015-Revert-WAF-schema-changes.patch
upstream-patches/0016-Un-deprecate-RDS-instance-name.patch
upstream-patches/0017-Catch-cty-panic-in-new-resourceTopicSubscriptionCust.patch
upstream-patches/0018-add-matchmaking-configuration-72.patch
upstream-patches/0019-fix-Adding-back-in-removeAddons.patch
upstream-patches/0020-Reverts-patches-to-S3BucketLegacy-and-GameLift.patch
upstream-patches/0021-Revert-Update-endpointHashIPAddress.patch
upstream-patches/0022-Fixup-eks-formatting.patch
upstream-patches/0023-Fixup-gamelift-context.patch
upstream-patches/0024-Change-default-descriptions-to-Managed-by-Pulumi.patch
upstream-patches/0025-remove-required-elements-from-schema-and-fix-tests-7.patch
upstream-patches/0026-Revert-Framework-conversions.patch
upstream-patches/0027-Temp-remove-cognito_identity_pool_roles_attachment-e.patch
upstream-patches/0028-Fix-elbv2-target-group-read.patch
upstream-patches/0029-Fix-spurrious-json-diff-for-redrive_policy.patch

Update upstream to include fix json diff for redrivePolicy

---

examples/examples_nodejs_test.go
examples/regress-1423/Pulumi.yaml
examples/regress-1423/index.ts
examples/regress-1423/package.json
examples/regress-1423/tsconfig.json
provider/resources.go

Fixes #1423 on top of the V6 branch.

Fix pulumi-aws#1423

---

Makefile

This change checks that the downloaded version of `pulumi-java-gen` matches the desired version.
Fixes #2297

Ensure that bin/pulumi-java-gen is up to date

---

provider/resources.go
sdk/dotnet/Organizations/GetOrganizationalUnits.cs
sdk/dotnet/Organizations/Outputs/GetOrganizationalUnitsChildResult.cs
sdk/go/aws/organizations/getOrganizationalUnits.go
sdk/go/aws/organizations/pulumiTypes.go
sdk/java/src/main/java/com/pulumi/aws/organizations/outputs/GetOrganizationalUnitsChild.java
sdk/java/src/main/java/com/pulumi/aws/organizations/outputs/GetOrganizationalUnitsResult.java
sdk/nodejs/organizations/getOrganizationalUnits.ts
sdk/nodejs/types/output.ts
sdk/python/pulumi_aws/controltower/control_tower_control.py
sdk/python/pulumi_aws/controltower/get_controls.py
sdk/python/pulumi_aws/organizations/get_organizational_units.py
sdk/python/pulumi_aws/organizations/outputs.py

Fix `"childrens"` for "aws_organizations_organizational_units"

---

examples/testdata/resources/Pulumi.yaml

Still need to record baselines.

Add tests for route53 resolverendpoint

---

Makefile

Fixes https://github.com/pulumi/ci-mgmt/issues/539

Switch from ssh to https for submodule

---

provider/resources.go
sdk/dotnet/NetworkFirewall/ResourcePolicy.cs
sdk/go/aws/networkfirewall/resourcePolicy.go
sdk/java/src/main/java/com/pulumi/aws/networkfirewall/ResourcePolicy.java
sdk/nodejs/networkfirewall/resourcePolicy.ts
sdk/python/pulumi_aws/networkfirewall/resource_policy.py

Fix import docs for aws_networkfirewall_resource_policy

---

sdk/nodejs/iam/principals.ts

Add state machine principal for nodejs sdk

---

examples/examples_nodejs_test.go
examples/regress-2818/Pulumi.yaml
examples/regress-2818/index.ts
examples/regress-2818/package.json
examples/regress-2818/tsconfig.json
provider/go.mod
provider/go.sum

Fixes #2818 
This needs to be reviewed together with https://github.com/pulumi/terraform-plugin-framework/commit/415dcb749c1638aa49c4e61cd68b0d93f4c25383
pulumi/terraform-plugin-framework fork was introduced for this fix specifically.

Fix panics when unknowns are passed into assumeRole

---

provider/resources.go

Fix https://github.com/pulumi/pulumi-aws/issues/2137 cc @jkodroff

Mark VpcAttachment as DeleteBeforeReplace

---

sdk/nodejs/lambda/lambdaMixins.ts

Refers to Issue [2901](https://github.com/pulumi/pulumi-aws/issues/2901)

Fix broken function serialization docs link

---

examples/callbackfunction/index.ts
examples/callbackfunction/package.json
sdk/nodejs/lambda/lambdaMixins.ts

- Support lifted inline policies in NodeJS `lambda.CallbackFunction` by @gsuess, originally in #2505 
- Fix configuration issues in e2e test

Support lifted inline policies in NodeJS lambda.CallbackFunction

---

README.md
sdk/python/README.md

Add endpoints option to README.md

---

provider/resources.go
sdk/dotnet/Ec2/Enums.cs
sdk/go/aws/ec2/pulumiEnums.go
sdk/java/src/main/java/com/pulumi/aws/ec2/enums/InstanceType.java
sdk/nodejs/types/enums/ec2/index.ts
sdk/python/pulumi_aws/ec2/_enums.py

Add r5dn.metal

---

provider/resources.go
sdk/dotnet/Enums.cs
sdk/go/aws/pulumiEnums.go
sdk/java/src/main/java/com/pulumi/aws/enums/Region.java
sdk/nodejs/types/enums/index.ts
sdk/python/pulumi_aws/_enums.py

> Follow up to https://github.com/pulumi/pulumi-aws/issues/3275.
Continuation of https://github.com/pulumi/pulumi-aws/pull/3283.

AWS Region `ca-west-1`

---

patches/0003-Add-S3-legacy-bucket-to-resources.patch
sdk/dotnet/S3/Bucket.cs
sdk/go/aws/s3/bucket.go
sdk/java/src/main/java/com/pulumi/aws/s3/Bucket.java
sdk/nodejs/s3/bucket.ts
sdk/python/pulumi_aws/s3/bucket.py

Continuation of https://github.com/pulumi/pulumi-aws/pull/3277.
Fixes Fixes https://github.com/pulumi/pulumi-aws/issues/3245.

Add precisions about using aws.s3.bucket with other cloud provider s3 integration

---

sdk/dotnet/Iot/Inputs/CaCertificateRegistrationConfigArgs.cs
sdk/dotnet/Iot/Inputs/CaCertificateRegistrationConfigGetArgs.cs
sdk/dotnet/Iot/Outputs/CaCertificateRegistrationConfig.cs
sdk/go/aws/iot/pulumiTypes.go
sdk/java/src/main/java/com/pulumi/aws/iot/inputs/CaCertificateRegistrationConfigArgs.java
sdk/java/src/main/java/com/pulumi/aws/iot/outputs/CaCertificateRegistrationConfig.java
sdk/nodejs/types/input.ts
sdk/nodejs/types/output.ts
sdk/python/pulumi_aws/iot/_inputs.py
sdk/python/pulumi_aws/iot/outputs.py

This PR was generated via `$ upgrade-provider pulumi/pulumi-aws --target-version 5.32.1`.
---
- Upgrading terraform-provider-aws from 5.32.0  to 5.32.1.
Fixes #3254

Upgrade terraform-provider-aws to v5.32.1

---

examples/examples_nodejs_test.go
examples/regress-2868/Pulumi.yaml
examples/regress-2868/index.ts
examples/regress-2868/package.json
examples/regress-2868/tsconfig.json

The actual fix is in the bridge but adding a test case here as the issue is highly upvoted.
Fixes #2868

Fix #2868: permanent diff on Congnito UserPool

---

.github/workflows/lint.yml
.github/workflows/master.yml
.github/workflows/nightly-test.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/run-acceptance-tests.yml

The result of running `make ci-mgmt`.
Fixes #3436

Update GH workflows

---

.ci-mgmt.yaml
.github/workflows/master.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/run-acceptance-tests.yml

Hopefully the last of https://github.com/pulumi/ci-mgmt/issues/772

Bump codecov action version

---

.ci-mgmt.yaml
.github/workflows/master.yml
.github/workflows/nightly-test.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/run-acceptance-tests.yml
.github/workflows/upgrade-bridge.yml
Makefile

Fixes https://github.com/pulumi/pulumi-aws/issues/3304
This bumps AWS to use default runners.
It also pulls in recent changes from ci-mgmt

Reduce runner size AWS

---

provider/provider_yaml_test.go

related to https://github.com/pulumi/pulumi-yaml/issues/561

fix: flaky test

---

examples/express/package.json

This example started failing in cron due to dependency issues. Upgrading to latest seems to get past the problem.

Fresh dependencies for the express example

---

.ci-mgmt.yaml
Makefile
sdk/dotnet/Ec2/SecurityGroup.cs
sdk/dotnet/Iot/GetEndpoint.cs
sdk/go/aws/ec2/securityGroup.go
sdk/go/aws/iot/getEndpoint.go
sdk/java/src/main/java/com/pulumi/aws/ec2/SecurityGroup.java
sdk/java/src/main/java/com/pulumi/aws/iot/IotFunctions.java
sdk/nodejs/ec2/securityGroup.ts
sdk/nodejs/iot/getEndpoint.ts
sdk/python/pulumi_aws/ec2/security_group.py
sdk/python/pulumi_aws/iot/get_endpoint.py

This change fixes examples that rendered incorrectly before that involved null, Kubernetes and local providers.

Upgrade dependencies affecting example rendering

---

provider/configure_test.go
provider/errors/expired_sso.txt
provider/errors/invalid_credentials.txt
provider/errors/no_credentials.txt

This URL has updated, let's use the new URL in the help text here.

fix URL in "learn more" text

---

examples/go.mod
examples/go.sum

Updating examples early to get https://github.com/pulumi/pulumi/pull/16663

chore: use pulumi v3.124.1 in examples

---

CONTRIBUTING.md

While we improve automation and documentation in the bridge for the upstream upgrade process, here are some notes on the de-facto process of doing these upgrades.

Add basic instructions for upstream upgrades

---

provider/resources.go

Deprecate WithPlanResourceChange and WithDiff

---

.mk/minimal_schema.mk

Fixes https://github.com/pulumi/pulumi-aws/issues/4844

Precompute minimal schema before make provider

---

sdk/go.mod

Refs https://github.com/pulumi/pulumi-aws/issues/4863

Retract v6.62.0

---

.ci-mgmt.yaml
.github/workflows/verify-release.yml

Enabling release verification
closes #1265

chore: enable release verifcation

---

.github/actions/download-codegen/action.yml
.github/actions/setup-tools/action.yml
.github/workflows/build_sdk.yml
.github/workflows/prerequisites.yml
.github/workflows/test.yml
.mk/minimal_schema.mk
Makefile

Update workflows to sync up with ci-mgmt.

chore: update GitHub Actions workflows

---

provider/doc_edits.go
sdk/dotnet/VpcLattice/ResourceConfiguration.cs
sdk/go/aws/vpclattice/resourceConfiguration.go
sdk/java/src/main/java/com/pulumi/aws/vpclattice/ResourceConfiguration.java
sdk/nodejs/vpclattice/resourceConfiguration.ts
sdk/python/pulumi_aws/vpclattice/resource_configuration.py

Fixes #https://github.com/pulumi/pulumi-aws/issues/5217
**Add doc edits rule**
- **make schema and build SDKs**

Fix incorrect example for Vpclattice ResourceConfiguration

---

examples/examples_nodejs_test.go

Fixes https://github.com/pulumi/pulumi-aws/issues/5395

chore: retry failed steps in regress-2555

---

provider/resources.go

[7.0.0-alpha]: Add a todo

---

.github/actions/download-prerequisites/action.yml
.github/actions/download-provider/action.yml
.github/actions/download-sdk/action.yml
.github/actions/setup-tools/action.yml
.github/workflows/lint.yml
.github/workflows/main-post-build.yml
.github/workflows/prerequisites.yml
.github/workflows/publish.yml
.github/workflows/test.yml
.github/workflows/verify-release.yml
examples/iam-policy-document/csharp/AWS.Webserver.csproj

Running this since it hasn't been done in a while

Update GitHub actions workflow

---

provider/types.go
sdk/dotnet/Ecr/Inputs/LifecyclePolicySelectionArgs.cs
sdk/dotnet/Ecr/Inputs/LifecyclePolicySelectionGetArgs.cs
sdk/go/aws/ecr/pulumiTypes.go
sdk/java/src/main/java/com/pulumi/aws/ecr/inputs/LifecyclePolicySelectionArgs.java
sdk/python/pulumi_aws/ecr/_inputs.py

[v7]: LifecyclePolicy has wrong type for `tagPrefixList`

---

docs/version-7-upgrade.md

adding additional instructions to the guide.

Update upgrade guide
